/* A Bison parser, made by GNU Bison 3.8.2.  */

/* Bison implementation for Yacc-like parsers in C

   Copyright (C) 1984, 1989-1990, 2000-2015, 2018-2021 Free Software Foundation,
   Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* C LALR(1) parser skeleton written by Richard Stallman, by
   simplifying the original so-called "semantic" parser.  */

/* DO NOT RELY ON FEATURES THAT ARE NOT DOCUMENTED in the manual,
   especially those whose name start with YY_ or yy_.  They are
   private implementation details that can be changed or removed.  */

/* All symbols defined below should begin with yy or YY, to avoid
   infringing on user name space.  This should be done even for local
   variables, as they might otherwise be expanded by user macros.
   There are some unavoidable exceptions within include files to
   define necessary library symbols; they are noted "INFRINGES ON
   USER NAME SPACE" below.  */

/* Identify Bison output, and Bison version.  */
#define YYBISON 30802

/* Bison version string.  */
#define YYBISON_VERSION "3.8.2"

/* Skeleton name.  */
#define YYSKELETON_NAME "yacc.c"

/* Pure parsers.  */
#define YYPURE 0

/* Push parsers.  */
#define YYPUSH 0

/* Pull parsers.  */
#define YYPULL 1




/* First part of user prologue.  */
#line 1 "/home/zhao/calculator/frontend/flexbison/Calculator.y"

#include <cstdio>
#include <cstring>
#include "../../common/ValueType.h"
// 词法分析头文件
#include "FlexLexer.h"

// bison生成的头文件
#include "BisonParser.h"

// 抽象语法树函数定义原型头文件
#include "AST.h"

// LR分析失败时所调用函数的原型声明
void yyerror(char * msg);


#line 89 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"

# ifndef YY_CAST
#  ifdef __cplusplus
#   define YY_CAST(Type, Val) static_cast<Type> (Val)
#   define YY_REINTERPRET_CAST(Type, Val) reinterpret_cast<Type> (Val)
#  else
#   define YY_CAST(Type, Val) ((Type) (Val))
#   define YY_REINTERPRET_CAST(Type, Val) ((Type) (Val))
#  endif
# endif
# ifndef YY_NULLPTR
#  if defined __cplusplus
#   if 201103L <= __cplusplus
#    define YY_NULLPTR nullptr
#   else
#    define YY_NULLPTR 0
#   endif
#  else
#   define YY_NULLPTR ((void*)0)
#  endif
# endif

#include "CalculatorBison.h"
/* Symbol kind.  */
enum yysymbol_kind_t
{
  YYSYMBOL_YYEMPTY = -2,
  YYSYMBOL_YYEOF = 0,                      /* "end of file"  */
  YYSYMBOL_YYerror = 1,                    /* error  */
  YYSYMBOL_YYUNDEF = 2,                    /* "invalid token"  */
  YYSYMBOL_T_DIGIT = 3,                    /* T_DIGIT  */
  YYSYMBOL_T_ID = 4,                       /* T_ID  */
  YYSYMBOL_T_FUNC = 5,                     /* T_FUNC  */
  YYSYMBOL_T_RETURN = 6,                   /* T_RETURN  */
  YYSYMBOL_T_IF = 7,                       /* T_IF  */
  YYSYMBOL_T_ELSE = 8,                     /* T_ELSE  */
  YYSYMBOL_T_WHILE = 9,                    /* T_WHILE  */
  YYSYMBOL_T_CONST = 10,                   /* T_CONST  */
  YYSYMBOL_T_VOID = 11,                    /* T_VOID  */
  YYSYMBOL_T_CONTINUE = 12,                /* T_CONTINUE  */
  YYSYMBOL_T_BREAK = 13,                   /* T_BREAK  */
  YYSYMBOL_T_INT = 14,                     /* T_INT  */
  YYSYMBOL_T_ADD = 15,                     /* T_ADD  */
  YYSYMBOL_T_SUB = 16,                     /* T_SUB  */
  YYSYMBOL_T_TIMES = 17,                   /* T_TIMES  */
  YYSYMBOL_T_DIV = 18,                     /* T_DIV  */
  YYSYMBOL_T_MOD = 19,                     /* T_MOD  */
  YYSYMBOL_T_EQUAL = 20,                   /* T_EQUAL  */
  YYSYMBOL_T_NOT_EQUAL = 21,               /* T_NOT_EQUAL  */
  YYSYMBOL_T_LESS_THAN = 22,               /* T_LESS_THAN  */
  YYSYMBOL_T_GREATER_THEN = 23,            /* T_GREATER_THEN  */
  YYSYMBOL_T_LESS_EQUAL = 24,              /* T_LESS_EQUAL  */
  YYSYMBOL_T_GREATER_EQUAL = 25,           /* T_GREATER_EQUAL  */
  YYSYMBOL_T_LOGICAL_AND = 26,             /* T_LOGICAL_AND  */
  YYSYMBOL_T_LOGICAL_OR = 27,              /* T_LOGICAL_OR  */
  YYSYMBOL_T_NOT = 28,                     /* T_NOT  */
  YYSYMBOL_29_ = 29,                       /* '('  */
  YYSYMBOL_30_ = 30,                       /* ')'  */
  YYSYMBOL_31_ = 31,                       /* ';'  */
  YYSYMBOL_32_ = 32,                       /* ','  */
  YYSYMBOL_33_ = 33,                       /* '['  */
  YYSYMBOL_34_ = 34,                       /* ']'  */
  YYSYMBOL_35_ = 35,                       /* '{'  */
  YYSYMBOL_36_ = 36,                       /* '}'  */
  YYSYMBOL_37_ = 37,                       /* '='  */
  YYSYMBOL_YYACCEPT = 38,                  /* $accept  */
  YYSYMBOL_CompileUnit = 39,               /* CompileUnit  */
  YYSYMBOL_FuncDef = 40,                   /* FuncDef  */
  YYSYMBOL_FuncFormalParams = 41,          /* FuncFormalParams  */
  YYSYMBOL_FuncFormalParam = 42,           /* FuncFormalParam  */
  YYSYMBOL_FuncBasicParam = 43,            /* FuncBasicParam  */
  YYSYMBOL_FuncBasicParamArrays = 44,      /* FuncBasicParamArrays  */
  YYSYMBOL_Block = 45,                     /* Block  */
  YYSYMBOL_BlockItemList = 46,             /* BlockItemList  */
  YYSYMBOL_BlockItem = 47,                 /* BlockItem  */
  YYSYMBOL_Statement = 48,                 /* Statement  */
  YYSYMBOL_Cond = 49,                      /* Cond  */
  YYSYMBOL_Expr = 50,                      /* Expr  */
  YYSYMBOL_RelExp = 51,                    /* RelExp  */
  YYSYMBOL_EqExp = 52,                     /* EqExp  */
  YYSYMBOL_LAndExp = 53,                   /* LAndExp  */
  YYSYMBOL_LOrExp = 54,                    /* LOrExp  */
  YYSYMBOL_Decl = 55,                      /* Decl  */
  YYSYMBOL_ConstExp = 56,                  /* ConstExp  */
  YYSYMBOL_InitVal = 57,                   /* InitVal  */
  YYSYMBOL_InitValList = 58,               /* InitValList  */
  YYSYMBOL_ConstDecl = 59,                 /* ConstDecl  */
  YYSYMBOL_ConstDefs = 60,                 /* ConstDefs  */
  YYSYMBOL_ConstInitVal = 61,              /* ConstInitVal  */
  YYSYMBOL_ConstDef = 62,                  /* ConstDef  */
  YYSYMBOL_VarDef = 63,                    /* VarDef  */
  YYSYMBOL_ArrayLists = 64,                /* ArrayLists  */
  YYSYMBOL_VarDecl = 65,                   /* VarDecl  */
  YYSYMBOL_VarDefs = 66,                   /* VarDefs  */
  YYSYMBOL_AddExp = 67,                    /* AddExp  */
  YYSYMBOL_MulExp = 68,                    /* MulExp  */
  YYSYMBOL_UnaryExp = 69,                  /* UnaryExp  */
  YYSYMBOL_PrimaryExp = 70,                /* PrimaryExp  */
  YYSYMBOL_LVal = 71,                      /* LVal  */
  YYSYMBOL_LValueList = 72,                /* LValueList  */
  YYSYMBOL_RealParamList = 73              /* RealParamList  */
};
typedef enum yysymbol_kind_t yysymbol_kind_t;




#ifdef short
# undef short
#endif

/* On compilers that do not define __PTRDIFF_MAX__ etc., make sure
   <limits.h> and (if available) <stdint.h> are included
   so that the code can choose integer types of a good width.  */

#ifndef __PTRDIFF_MAX__
# include <limits.h> /* INFRINGES ON USER NAME SPACE */
# if defined __STDC_VERSION__ && 199901 <= __STDC_VERSION__
#  include <stdint.h> /* INFRINGES ON USER NAME SPACE */
#  define YY_STDINT_H
# endif
#endif

/* Narrow types that promote to a signed type and that can represent a
   signed or unsigned integer of at least N bits.  In tables they can
   save space and decrease cache pressure.  Promoting to a signed type
   helps avoid bugs in integer arithmetic.  */

#ifdef __INT_LEAST8_MAX__
typedef __INT_LEAST8_TYPE__ yytype_int8;
#elif defined YY_STDINT_H
typedef int_least8_t yytype_int8;
#else
typedef signed char yytype_int8;
#endif

#ifdef __INT_LEAST16_MAX__
typedef __INT_LEAST16_TYPE__ yytype_int16;
#elif defined YY_STDINT_H
typedef int_least16_t yytype_int16;
#else
typedef short yytype_int16;
#endif

/* Work around bug in HP-UX 11.23, which defines these macros
   incorrectly for preprocessor constants.  This workaround can likely
   be removed in 2023, as HPE has promised support for HP-UX 11.23
   (aka HP-UX 11i v2) only through the end of 2022; see Table 2 of
   <https://h20195.www2.hpe.com/V2/getpdf.aspx/4AA4-7673ENW.pdf>.  */
#ifdef __hpux
# undef UINT_LEAST8_MAX
# undef UINT_LEAST16_MAX
# define UINT_LEAST8_MAX 255
# define UINT_LEAST16_MAX 65535
#endif

#if defined __UINT_LEAST8_MAX__ && __UINT_LEAST8_MAX__ <= __INT_MAX__
typedef __UINT_LEAST8_TYPE__ yytype_uint8;
#elif (!defined __UINT_LEAST8_MAX__ && defined YY_STDINT_H \
       && UINT_LEAST8_MAX <= INT_MAX)
typedef uint_least8_t yytype_uint8;
#elif !defined __UINT_LEAST8_MAX__ && UCHAR_MAX <= INT_MAX
typedef unsigned char yytype_uint8;
#else
typedef short yytype_uint8;
#endif

#if defined __UINT_LEAST16_MAX__ && __UINT_LEAST16_MAX__ <= __INT_MAX__
typedef __UINT_LEAST16_TYPE__ yytype_uint16;
#elif (!defined __UINT_LEAST16_MAX__ && defined YY_STDINT_H \
       && UINT_LEAST16_MAX <= INT_MAX)
typedef uint_least16_t yytype_uint16;
#elif !defined __UINT_LEAST16_MAX__ && USHRT_MAX <= INT_MAX
typedef unsigned short yytype_uint16;
#else
typedef int yytype_uint16;
#endif

#ifndef YYPTRDIFF_T
# if defined __PTRDIFF_TYPE__ && defined __PTRDIFF_MAX__
#  define YYPTRDIFF_T __PTRDIFF_TYPE__
#  define YYPTRDIFF_MAXIMUM __PTRDIFF_MAX__
# elif defined PTRDIFF_MAX
#  ifndef ptrdiff_t
#   include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  endif
#  define YYPTRDIFF_T ptrdiff_t
#  define YYPTRDIFF_MAXIMUM PTRDIFF_MAX
# else
#  define YYPTRDIFF_T long
#  define YYPTRDIFF_MAXIMUM LONG_MAX
# endif
#endif

#ifndef YYSIZE_T
# ifdef __SIZE_TYPE__
#  define YYSIZE_T __SIZE_TYPE__
# elif defined size_t
#  define YYSIZE_T size_t
# elif defined __STDC_VERSION__ && 199901 <= __STDC_VERSION__
#  include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  define YYSIZE_T size_t
# else
#  define YYSIZE_T unsigned
# endif
#endif

#define YYSIZE_MAXIMUM                                  \
  YY_CAST (YYPTRDIFF_T,                                 \
           (YYPTRDIFF_MAXIMUM < YY_CAST (YYSIZE_T, -1)  \
            ? YYPTRDIFF_MAXIMUM                         \
            : YY_CAST (YYSIZE_T, -1)))

#define YYSIZEOF(X) YY_CAST (YYPTRDIFF_T, sizeof (X))


/* Stored state numbers (used for stacks). */
typedef yytype_uint8 yy_state_t;

/* State numbers in computations.  */
typedef int yy_state_fast_t;

#ifndef YY_
# if defined YYENABLE_NLS && YYENABLE_NLS
#  if ENABLE_NLS
#   include <libintl.h> /* INFRINGES ON USER NAME SPACE */
#   define YY_(Msgid) dgettext ("bison-runtime", Msgid)
#  endif
# endif
# ifndef YY_
#  define YY_(Msgid) Msgid
# endif
#endif


#ifndef YY_ATTRIBUTE_PURE
# if defined __GNUC__ && 2 < __GNUC__ + (96 <= __GNUC_MINOR__)
#  define YY_ATTRIBUTE_PURE __attribute__ ((__pure__))
# else
#  define YY_ATTRIBUTE_PURE
# endif
#endif

#ifndef YY_ATTRIBUTE_UNUSED
# if defined __GNUC__ && 2 < __GNUC__ + (7 <= __GNUC_MINOR__)
#  define YY_ATTRIBUTE_UNUSED __attribute__ ((__unused__))
# else
#  define YY_ATTRIBUTE_UNUSED
# endif
#endif

/* Suppress unused-variable warnings by "using" E.  */
#if ! defined lint || defined __GNUC__
# define YY_USE(E) ((void) (E))
#else
# define YY_USE(E) /* empty */
#endif

/* Suppress an incorrect diagnostic about yylval being uninitialized.  */
#if defined __GNUC__ && ! defined __ICC && 406 <= __GNUC__ * 100 + __GNUC_MINOR__
# if __GNUC__ * 100 + __GNUC_MINOR__ < 407
#  define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN                           \
    _Pragma ("GCC diagnostic push")                                     \
    _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"")
# else
#  define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN                           \
    _Pragma ("GCC diagnostic push")                                     \
    _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"")              \
    _Pragma ("GCC diagnostic ignored \"-Wmaybe-uninitialized\"")
# endif
# define YY_IGNORE_MAYBE_UNINITIALIZED_END      \
    _Pragma ("GCC diagnostic pop")
#else
# define YY_INITIAL_VALUE(Value) Value
#endif
#ifndef YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_END
#endif
#ifndef YY_INITIAL_VALUE
# define YY_INITIAL_VALUE(Value) /* Nothing. */
#endif

#if defined __cplusplus && defined __GNUC__ && ! defined __ICC && 6 <= __GNUC__
# define YY_IGNORE_USELESS_CAST_BEGIN                          \
    _Pragma ("GCC diagnostic push")                            \
    _Pragma ("GCC diagnostic ignored \"-Wuseless-cast\"")
# define YY_IGNORE_USELESS_CAST_END            \
    _Pragma ("GCC diagnostic pop")
#endif
#ifndef YY_IGNORE_USELESS_CAST_BEGIN
# define YY_IGNORE_USELESS_CAST_BEGIN
# define YY_IGNORE_USELESS_CAST_END
#endif


#define YY_ASSERT(E) ((void) (0 && (E)))

#if !defined yyoverflow

/* The parser invokes alloca or malloc; define the necessary symbols.  */

# ifdef YYSTACK_USE_ALLOCA
#  if YYSTACK_USE_ALLOCA
#   ifdef __GNUC__
#    define YYSTACK_ALLOC __builtin_alloca
#   elif defined __BUILTIN_VA_ARG_INCR
#    include <alloca.h> /* INFRINGES ON USER NAME SPACE */
#   elif defined _AIX
#    define YYSTACK_ALLOC __alloca
#   elif defined _MSC_VER
#    include <malloc.h> /* INFRINGES ON USER NAME SPACE */
#    define alloca _alloca
#   else
#    define YYSTACK_ALLOC alloca
#    if ! defined _ALLOCA_H && ! defined EXIT_SUCCESS
#     include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
      /* Use EXIT_SUCCESS as a witness for stdlib.h.  */
#     ifndef EXIT_SUCCESS
#      define EXIT_SUCCESS 0
#     endif
#    endif
#   endif
#  endif
# endif

# ifdef YYSTACK_ALLOC
   /* Pacify GCC's 'empty if-body' warning.  */
#  define YYSTACK_FREE(Ptr) do { /* empty */; } while (0)
#  ifndef YYSTACK_ALLOC_MAXIMUM
    /* The OS might guarantee only one guard page at the bottom of the stack,
       and a page size can be as small as 4096 bytes.  So we cannot safely
       invoke alloca (N) if N exceeds 4096.  Use a slightly smaller number
       to allow for a few compiler-allocated temporary stack slots.  */
#   define YYSTACK_ALLOC_MAXIMUM 4032 /* reasonable circa 2006 */
#  endif
# else
#  define YYSTACK_ALLOC YYMALLOC
#  define YYSTACK_FREE YYFREE
#  ifndef YYSTACK_ALLOC_MAXIMUM
#   define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#  endif
#  if (defined __cplusplus && ! defined EXIT_SUCCESS \
       && ! ((defined YYMALLOC || defined malloc) \
             && (defined YYFREE || defined free)))
#   include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
#   ifndef EXIT_SUCCESS
#    define EXIT_SUCCESS 0
#   endif
#  endif
#  ifndef YYMALLOC
#   define YYMALLOC malloc
#   if ! defined malloc && ! defined EXIT_SUCCESS
void *malloc (YYSIZE_T); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
#  ifndef YYFREE
#   define YYFREE free
#   if ! defined free && ! defined EXIT_SUCCESS
void free (void *); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
# endif
#endif /* !defined yyoverflow */

#if (! defined yyoverflow \
     && (! defined __cplusplus \
         || (defined YYSTYPE_IS_TRIVIAL && YYSTYPE_IS_TRIVIAL)))

/* A type that is properly aligned for any stack member.  */
union yyalloc
{
  yy_state_t yyss_alloc;
  YYSTYPE yyvs_alloc;
};

/* The size of the maximum gap between one aligned stack and the next.  */
# define YYSTACK_GAP_MAXIMUM (YYSIZEOF (union yyalloc) - 1)

/* The size of an array large to enough to hold all stacks, each with
   N elements.  */
# define YYSTACK_BYTES(N) \
     ((N) * (YYSIZEOF (yy_state_t) + YYSIZEOF (YYSTYPE)) \
      + YYSTACK_GAP_MAXIMUM)

# define YYCOPY_NEEDED 1

/* Relocate STACK from its old location to the new one.  The
   local variables YYSIZE and YYSTACKSIZE give the old and new number of
   elements in the stack, and YYPTR gives the new location of the
   stack.  Advance YYPTR to a properly aligned location for the next
   stack.  */
# define YYSTACK_RELOCATE(Stack_alloc, Stack)                           \
    do                                                                  \
      {                                                                 \
        YYPTRDIFF_T yynewbytes;                                         \
        YYCOPY (&yyptr->Stack_alloc, Stack, yysize);                    \
        Stack = &yyptr->Stack_alloc;                                    \
        yynewbytes = yystacksize * YYSIZEOF (*Stack) + YYSTACK_GAP_MAXIMUM; \
        yyptr += yynewbytes / YYSIZEOF (*yyptr);                        \
      }                                                                 \
    while (0)

#endif

#if defined YYCOPY_NEEDED && YYCOPY_NEEDED
/* Copy COUNT objects from SRC to DST.  The source and destination do
   not overlap.  */
# ifndef YYCOPY
#  if defined __GNUC__ && 1 < __GNUC__
#   define YYCOPY(Dst, Src, Count) \
      __builtin_memcpy (Dst, Src, YY_CAST (YYSIZE_T, (Count)) * sizeof (*(Src)))
#  else
#   define YYCOPY(Dst, Src, Count)              \
      do                                        \
        {                                       \
          YYPTRDIFF_T yyi;                      \
          for (yyi = 0; yyi < (Count); yyi++)   \
            (Dst)[yyi] = (Src)[yyi];            \
        }                                       \
      while (0)
#  endif
# endif
#endif /* !YYCOPY_NEEDED */

/* YYFINAL -- State number of the termination state.  */
#define YYFINAL  61
/* YYLAST -- Last index in YYTABLE.  */
#define YYLAST   318

/* YYNTOKENS -- Number of terminals.  */
#define YYNTOKENS  38
/* YYNNTS -- Number of nonterminals.  */
#define YYNNTS  36
/* YYNRULES -- Number of rules.  */
#define YYNRULES  104
/* YYNSTATES -- Number of states.  */
#define YYNSTATES  195

/* YYMAXUTOK -- Last valid token kind.  */
#define YYMAXUTOK   283


/* YYTRANSLATE(TOKEN-NUM) -- Symbol number corresponding to TOKEN-NUM
   as returned by yylex, with out-of-bounds checking.  */
#define YYTRANSLATE(YYX)                                \
  (0 <= (YYX) && (YYX) <= YYMAXUTOK                     \
   ? YY_CAST (yysymbol_kind_t, yytranslate[YYX])        \
   : YYSYMBOL_YYUNDEF)

/* YYTRANSLATE[TOKEN-NUM] -- Symbol number corresponding to TOKEN-NUM
   as returned by yylex.  */
static const yytype_int8 yytranslate[] =
{
       0,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
      29,    30,     2,     2,    32,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,    31,
       2,    37,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,    33,     2,    34,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,    35,     2,    36,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     1,     2,     3,     4,
       5,     6,     7,     8,     9,    10,    11,    12,    13,    14,
      15,    16,    17,    18,    19,    20,    21,    22,    23,    24,
      25,    26,    27,    28
};

#if YYDEBUG
/* YYRLINE[YYN] -- Source line where rule number YYN was defined.  */
static const yytype_int16 yyrline[] =
{
       0,    74,    74,    78,    82,    85,    88,    94,   101,   104,
     107,   111,   115,   119,   123,   127,   131,   135,   142,   145,
     151,   157,   160,   168,   175,   182,   191,   195,   202,   207,
     216,   220,   228,   240,   247,   254,   258,   262,   266,   270,
     274,   278,   282,   286,   292,   300,   305,   309,   314,   318,
     322,   328,   332,   337,   342,   346,   351,   355,   361,   366,
     376,   382,   387,   391,   397,   402,   408,   421,   427,   434,
     438,   442,   448,   467,   476,   483,   494,   501,   509,   516,
     526,   534,   539,   545,   551,   557,   561,   565,   569,   573,
     595,   598,   602,   606,   610,   615,   622,   626,   632,   639,
     646,   653,   661,   671,   674
};
#endif

/** Accessing symbol of state STATE.  */
#define YY_ACCESSING_SYMBOL(State) YY_CAST (yysymbol_kind_t, yystos[State])

#if YYDEBUG || 0
/* The user-facing name of the symbol whose (internal) number is
   YYSYMBOL.  No bounds checking.  */
static const char *yysymbol_name (yysymbol_kind_t yysymbol) YY_ATTRIBUTE_UNUSED;

/* YYTNAME[SYMBOL-NUM] -- String name of the symbol SYMBOL-NUM.
   First, the terminals, then, starting at YYNTOKENS, nonterminals.  */
static const char *const yytname[] =
{
  "\"end of file\"", "error", "\"invalid token\"", "T_DIGIT", "T_ID",
  "T_FUNC", "T_RETURN", "T_IF", "T_ELSE", "T_WHILE", "T_CONST", "T_VOID",
  "T_CONTINUE", "T_BREAK", "T_INT", "T_ADD", "T_SUB", "T_TIMES", "T_DIV",
  "T_MOD", "T_EQUAL", "T_NOT_EQUAL", "T_LESS_THAN", "T_GREATER_THEN",
  "T_LESS_EQUAL", "T_GREATER_EQUAL", "T_LOGICAL_AND", "T_LOGICAL_OR",
  "T_NOT", "'('", "')'", "';'", "','", "'['", "']'", "'{'", "'}'", "'='",
  "$accept", "CompileUnit", "FuncDef", "FuncFormalParams",
  "FuncFormalParam", "FuncBasicParam", "FuncBasicParamArrays", "Block",
  "BlockItemList", "BlockItem", "Statement", "Cond", "Expr", "RelExp",
  "EqExp", "LAndExp", "LOrExp", "Decl", "ConstExp", "InitVal",
  "InitValList", "ConstDecl", "ConstDefs", "ConstInitVal", "ConstDef",
  "VarDef", "ArrayLists", "VarDecl", "VarDefs", "AddExp", "MulExp",
  "UnaryExp", "PrimaryExp", "LVal", "LValueList", "RealParamList", YY_NULLPTR
};

static const char *
yysymbol_name (yysymbol_kind_t yysymbol)
{
  return yytname[yysymbol];
}
#endif

#define YYPACT_NINF (-109)

#define yypact_value_is_default(Yyn) \
  ((Yyn) == YYPACT_NINF)

#define YYTABLE_NINF (-1)

#define yytable_value_is_error(Yyn) \
  0

/* YYPACT[STATE-NUM] -- Index in YYTABLE of the portion describing
   STATE-NUM.  */
static const yytype_int16 yypact[] =
{
     230,  -109,    -7,     5,   284,   -12,    -6,    23,    58,     9,
      33,    81,   201,   201,   201,   201,  -109,    91,   142,  -109,
    -109,  -109,    59,   137,   120,    67,    72,  -109,  -109,  -109,
     153,    54,  -109,  -109,    65,   288,   201,    75,    87,  -109,
      79,  -109,   201,   201,   121,   104,  -109,  -109,   -13,  -109,
     143,  -109,  -109,  -109,   134,   162,  -109,   179,  -109,  -109,
    -109,  -109,  -109,  -109,  -109,  -109,   201,   201,   201,   201,
     201,   201,   201,   201,   201,   201,   201,   201,   201,   201,
    -109,  -109,    22,   138,   201,    16,  -109,   157,    72,   160,
      37,   149,  -109,    29,    36,   201,   247,    46,  -109,   162,
    -109,    49,  -109,  -109,   153,   153,   153,   153,   137,   137,
     120,    67,    54,    54,  -109,  -109,  -109,   107,  -109,   201,
    -109,   164,   199,   171,    25,  -109,  -109,    32,    32,   251,
      51,  -109,   121,    -2,   102,    34,   133,   175,   153,   108,
    -109,  -109,   201,   247,  -109,  -109,  -109,  -109,   180,  -109,
     171,   208,   215,  -109,   196,  -109,  -109,   251,  -109,  -109,
    -109,    56,  -109,  -109,    78,  -109,  -109,  -109,    82,   192,
    -109,   268,   194,  -109,  -109,    32,  -109,    85,  -109,  -109,
    -109,  -109,  -109,   247,  -109,  -109,  -109,   204,   201,  -109,
    -109,  -109,  -109,   213,  -109
};

/* YYDEFACT[STATE-NUM] -- Default reduction number in state STATE-NUM.
   Performed when YYTABLE does not specify something else to do.  Zero
   means the default is an error.  */
static const yytype_int8 yydefact[] =
{
       0,    97,    99,     0,     0,     0,     0,     0,     0,     0,
       0,     0,     0,     0,     0,     0,    35,     0,     0,     2,
      43,     3,    34,    51,    54,    56,    45,     6,    58,    59,
      46,    85,    89,    90,    98,     0,     0,   100,     0,    36,
       0,    98,     0,     0,     0,     0,    42,    41,    74,    81,
       0,    93,    94,    95,     0,     0,    26,     0,    28,    30,
      31,     1,     4,     5,     7,    33,     0,     0,     0,     0,
       0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
      91,   103,     0,     0,     0,     0,    37,     0,    44,     0,
       0,     0,    67,     0,     0,     0,     0,    76,    80,     0,
      96,    74,    27,    29,    47,    48,    49,    50,    52,    53,
      55,    57,    83,    84,    86,    87,    88,     0,    92,     0,
     101,     0,     0,     0,     0,    18,    20,     0,     0,     0,
       0,    66,     0,     0,     0,     0,     0,     0,    60,     0,
      61,    75,     0,     0,    82,    32,   104,   102,    21,     8,
       0,     0,    39,    40,     0,    69,    72,     0,    68,    11,
      10,     0,    16,    14,     0,    78,    63,    64,     0,     0,
      77,     0,    22,     9,    19,     0,    71,     0,    73,    13,
      12,    17,    15,     0,    62,    79,    23,     0,     0,    38,
      70,    65,    24,     0,    25
};

/* YYPGOTO[NTERM-NUM].  */
static const yytype_int16 yypgoto[] =
{
    -109,  -109,   210,   103,    97,  -109,  -109,  -108,  -109,   195,
       3,   206,    -4,   131,   181,   183,   176,    10,   -91,   -94,
     106,  -109,  -109,   100,   132,   169,   184,  -109,  -109,   -61,
     146,     0,  -109,     1,  -109,  -109
};

/* YYDEFGOTO[NTERM-NUM].  */
static const yytype_uint8 yydefgoto[] =
{
       0,    18,    19,   124,   125,   126,   172,    20,    57,    58,
      59,    87,    22,    23,    24,    25,    26,    60,   155,   167,
     168,    28,    91,   156,    92,    49,    97,    29,    50,    30,
      31,    32,    33,    41,    37,    82
};

/* YYTABLE[YYPACT[STATE-NUM]] -- What to do in state STATE-NUM.  If
   positive, shift that token.  If negative, reduce the rule whose
   number is the opposite.  If YYTABLE_NINF, syntax error.  */
static const yytype_uint8 yytable[] =
{
      40,    34,   141,    21,   137,   104,   105,   106,   107,    38,
      27,    54,    51,    52,    53,   149,    94,    42,    34,    34,
      95,    63,    35,    43,    96,   160,    36,   163,    64,   159,
     122,    81,    83,    17,   138,     1,     2,    44,     4,     5,
      46,     6,   173,   122,     9,    10,   123,    12,    13,   170,
     122,   169,   118,   180,   119,   150,   182,   151,    34,   133,
      14,    15,    45,    16,    47,   162,   135,    17,   138,    17,
      95,    76,    77,    78,   129,   117,   114,   115,   116,   142,
     121,   138,    95,   143,   142,    48,    96,   179,   157,   191,
      65,    17,   140,    72,     1,     2,   138,     4,     5,    73,
       6,     7,    79,     9,    10,    55,    12,    13,    84,   181,
      86,     1,     2,    17,   183,   146,    85,   183,   184,    14,
      15,   190,    16,    12,    13,    90,    17,    56,    34,    34,
     152,   153,   161,    93,   151,   140,    14,    15,   145,   140,
      70,    71,    61,   139,   166,     1,     2,     3,     4,     5,
     140,     6,     7,     8,     9,    10,    11,    12,    13,    66,
      67,    68,    69,   164,   100,   151,   101,   187,    74,    75,
      14,    15,   120,    16,    98,    99,    34,    17,   189,   140,
     131,   132,     1,     2,   193,     4,     5,   127,     6,     7,
     128,     9,    10,    55,    12,    13,   134,   136,   147,     1,
       2,   108,   109,   148,     1,     2,    17,    14,    15,   165,
      16,    12,    13,   171,    17,   102,    12,    13,    88,    88,
     112,   113,   122,   175,    14,    15,   185,   188,    62,    14,
      15,   139,   176,     1,     2,     3,     4,     5,   192,     6,
       7,     8,     9,    10,    11,    12,    13,   194,   174,    89,
       1,     2,   103,   110,     1,     2,   111,   178,    14,    15,
     177,    16,    12,    13,   158,    17,    12,    13,   144,     0,
       0,     1,     2,     0,   130,    14,    15,     0,     0,    14,
      15,     0,   139,    12,    13,     0,   154,     1,     2,     0,
       0,     1,     2,     0,     0,     0,    14,    15,     0,    12,
      13,     0,   186,    12,    13,     0,     0,     0,     0,     0,
       0,     0,    14,    15,     0,    39,    14,    15,    80
};

static const yytype_int16 yycheck[] =
{
       4,     0,    96,     0,    95,    66,    67,    68,    69,     4,
       0,    15,    12,    13,    14,   123,    29,    29,    17,    18,
      33,    18,    29,    29,    37,   133,    33,   135,    18,    31,
      14,    35,    36,    35,    95,     3,     4,    14,     6,     7,
      31,     9,   150,    14,    12,    13,    30,    15,    16,   143,
      14,   142,    30,   161,    32,    30,   164,    32,    57,    30,
      28,    29,     4,    31,    31,    31,    30,    35,   129,    35,
      33,    17,    18,    19,    37,    79,    76,    77,    78,    33,
      84,   142,    33,    37,    33,     4,    37,    31,    37,   183,
      31,    35,    96,    26,     3,     4,   157,     6,     7,    27,
       9,    10,    37,    12,    13,    14,    15,    16,    33,    31,
      31,     3,     4,    35,    32,   119,    29,    32,    36,    28,
      29,    36,    31,    15,    16,     4,    35,    36,   127,   128,
     127,   128,    30,    29,    32,   139,    28,    29,    31,   143,
      20,    21,     0,    35,    36,     3,     4,     5,     6,     7,
     154,     9,    10,    11,    12,    13,    14,    15,    16,    22,
      23,    24,    25,    30,    30,    32,     4,   171,    15,    16,
      28,    29,    34,    31,    31,    32,   175,    35,   175,   183,
      31,    32,     3,     4,   188,     6,     7,    30,     9,    10,
      30,    12,    13,    14,    15,    16,    93,    94,    34,     3,
       4,    70,    71,     4,     3,     4,    35,    28,    29,    34,
      31,    15,    16,    33,    35,    36,    15,    16,    42,    43,
      74,    75,    14,     8,    28,    29,    34,    33,    18,    28,
      29,    35,    36,     3,     4,     5,     6,     7,    34,     9,
      10,    11,    12,    13,    14,    15,    16,    34,   151,    43,
       3,     4,    57,    72,     3,     4,    73,   157,    28,    29,
     154,    31,    15,    16,   132,    35,    15,    16,    99,    -1,
      -1,     3,     4,    -1,    90,    28,    29,    -1,    -1,    28,
      29,    -1,    35,    15,    16,    -1,    35,     3,     4,    -1,
      -1,     3,     4,    -1,    -1,    -1,    28,    29,    -1,    15,
      16,    -1,    34,    15,    16,    -1,    -1,    -1,    -1,    -1,
      -1,    -1,    28,    29,    -1,    31,    28,    29,    30
};

/* YYSTOS[STATE-NUM] -- The symbol kind of the accessing symbol of
   state STATE-NUM.  */
static const yytype_int8 yystos[] =
{
       0,     3,     4,     5,     6,     7,     9,    10,    11,    12,
      13,    14,    15,    16,    28,    29,    31,    35,    39,    40,
      45,    48,    50,    51,    52,    53,    54,    55,    59,    65,
      67,    68,    69,    70,    71,    29,    33,    72,     4,    31,
      50,    71,    29,    29,    14,     4,    31,    31,     4,    63,
      66,    69,    69,    69,    50,    14,    36,    46,    47,    48,
      55,     0,    40,    48,    55,    31,    22,    23,    24,    25,
      20,    21,    26,    27,    15,    16,    17,    18,    19,    37,
      30,    50,    73,    50,    33,    29,    31,    49,    54,    49,
       4,    60,    62,    29,    29,    33,    37,    64,    31,    32,
      30,     4,    36,    47,    67,    67,    67,    67,    51,    51,
      52,    53,    68,    68,    69,    69,    69,    50,    30,    32,
      34,    50,    14,    30,    41,    42,    43,    30,    30,    37,
      64,    31,    32,    30,    41,    30,    41,    56,    67,    35,
      50,    57,    33,    37,    63,    31,    50,    34,     4,    45,
      30,    32,    48,    48,    35,    56,    61,    37,    62,    31,
      45,    30,    31,    45,    30,    34,    36,    57,    58,    56,
      57,    33,    44,    45,    42,     8,    36,    58,    61,    31,
      45,    31,    45,    32,    36,    34,    34,    50,    33,    48,
      36,    57,    34,    50,    34
};

/* YYR1[RULE-NUM] -- Symbol kind of the left-hand side of rule RULE-NUM.  */
static const yytype_int8 yyr1[] =
{
       0,    38,    39,    39,    39,    39,    39,    39,    40,    40,
      40,    40,    40,    40,    40,    40,    40,    40,    41,    41,
      42,    43,    43,    44,    44,    44,    45,    45,    46,    46,
      47,    47,    48,    48,    48,    48,    48,    48,    48,    48,
      48,    48,    48,    48,    49,    50,    51,    51,    51,    51,
      51,    52,    52,    52,    53,    53,    54,    54,    55,    55,
      56,    57,    57,    57,    58,    58,    59,    60,    60,    61,
      61,    61,    62,    62,    63,    63,    63,    63,    64,    64,
      65,    66,    66,    67,    67,    67,    68,    68,    68,    68,
      69,    69,    69,    69,    69,    69,    70,    70,    70,    71,
      71,    72,    72,    73,    73
};

/* YYR2[RULE-NUM] -- Number of symbols on the right-hand side of rule RULE-NUM.  */
static const yytype_int8 yyr2[] =
{
       0,     2,     1,     1,     2,     2,     1,     2,     5,     6,
       5,     5,     6,     6,     5,     6,     5,     6,     1,     3,
       1,     2,     3,     2,     3,     4,     2,     3,     1,     2,
       1,     1,     4,     2,     1,     1,     2,     3,     7,     5,
       5,     2,     2,     1,     1,     1,     1,     3,     3,     3,
       3,     1,     3,     3,     1,     3,     1,     3,     1,     1,
       1,     1,     3,     2,     1,     3,     4,     1,     3,     1,
       3,     2,     3,     4,     1,     3,     2,     4,     3,     4,
       3,     1,     3,     3,     3,     1,     3,     3,     3,     1,
       1,     3,     4,     2,     2,     2,     3,     1,     1,     1,
       2,     3,     4,     1,     3
};


enum { YYENOMEM = -2 };

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (yychar = YYEMPTY)

#define YYACCEPT        goto yyacceptlab
#define YYABORT         goto yyabortlab
#define YYERROR         goto yyerrorlab
#define YYNOMEM         goto yyexhaustedlab


#define YYRECOVERING()  (!!yyerrstatus)

#define YYBACKUP(Token, Value)                                    \
  do                                                              \
    if (yychar == YYEMPTY)                                        \
      {                                                           \
        yychar = (Token);                                         \
        yylval = (Value);                                         \
        YYPOPSTACK (yylen);                                       \
        yystate = *yyssp;                                         \
        goto yybackup;                                            \
      }                                                           \
    else                                                          \
      {                                                           \
        yyerror (YY_("syntax error: cannot back up")); \
        YYERROR;                                                  \
      }                                                           \
  while (0)

/* Backward compatibility with an undocumented macro.
   Use YYerror or YYUNDEF. */
#define YYERRCODE YYUNDEF


/* Enable debugging if requested.  */
#if YYDEBUG

# ifndef YYFPRINTF
#  include <stdio.h> /* INFRINGES ON USER NAME SPACE */
#  define YYFPRINTF fprintf
# endif

# define YYDPRINTF(Args)                        \
do {                                            \
  if (yydebug)                                  \
    YYFPRINTF Args;                             \
} while (0)




# define YY_SYMBOL_PRINT(Title, Kind, Value, Location)                    \
do {                                                                      \
  if (yydebug)                                                            \
    {                                                                     \
      YYFPRINTF (stderr, "%s ", Title);                                   \
      yy_symbol_print (stderr,                                            \
                  Kind, Value); \
      YYFPRINTF (stderr, "\n");                                           \
    }                                                                     \
} while (0)


/*-----------------------------------.
| Print this symbol's value on YYO.  |
`-----------------------------------*/

static void
yy_symbol_value_print (FILE *yyo,
                       yysymbol_kind_t yykind, YYSTYPE const * const yyvaluep)
{
  FILE *yyoutput = yyo;
  YY_USE (yyoutput);
  if (!yyvaluep)
    return;
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  YY_USE (yykind);
  YY_IGNORE_MAYBE_UNINITIALIZED_END
}


/*---------------------------.
| Print this symbol on YYO.  |
`---------------------------*/

static void
yy_symbol_print (FILE *yyo,
                 yysymbol_kind_t yykind, YYSTYPE const * const yyvaluep)
{
  YYFPRINTF (yyo, "%s %s (",
             yykind < YYNTOKENS ? "token" : "nterm", yysymbol_name (yykind));

  yy_symbol_value_print (yyo, yykind, yyvaluep);
  YYFPRINTF (yyo, ")");
}

/*------------------------------------------------------------------.
| yy_stack_print -- Print the state stack from its BOTTOM up to its |
| TOP (included).                                                   |
`------------------------------------------------------------------*/

static void
yy_stack_print (yy_state_t *yybottom, yy_state_t *yytop)
{
  YYFPRINTF (stderr, "Stack now");
  for (; yybottom <= yytop; yybottom++)
    {
      int yybot = *yybottom;
      YYFPRINTF (stderr, " %d", yybot);
    }
  YYFPRINTF (stderr, "\n");
}

# define YY_STACK_PRINT(Bottom, Top)                            \
do {                                                            \
  if (yydebug)                                                  \
    yy_stack_print ((Bottom), (Top));                           \
} while (0)


/*------------------------------------------------.
| Report that the YYRULE is going to be reduced.  |
`------------------------------------------------*/

static void
yy_reduce_print (yy_state_t *yyssp, YYSTYPE *yyvsp,
                 int yyrule)
{
  int yylno = yyrline[yyrule];
  int yynrhs = yyr2[yyrule];
  int yyi;
  YYFPRINTF (stderr, "Reducing stack by rule %d (line %d):\n",
             yyrule - 1, yylno);
  /* The symbols being reduced.  */
  for (yyi = 0; yyi < yynrhs; yyi++)
    {
      YYFPRINTF (stderr, "   $%d = ", yyi + 1);
      yy_symbol_print (stderr,
                       YY_ACCESSING_SYMBOL (+yyssp[yyi + 1 - yynrhs]),
                       &yyvsp[(yyi + 1) - (yynrhs)]);
      YYFPRINTF (stderr, "\n");
    }
}

# define YY_REDUCE_PRINT(Rule)          \
do {                                    \
  if (yydebug)                          \
    yy_reduce_print (yyssp, yyvsp, Rule); \
} while (0)

/* Nonzero means print parse trace.  It is left uninitialized so that
   multiple parsers can coexist.  */
int yydebug;
#else /* !YYDEBUG */
# define YYDPRINTF(Args) ((void) 0)
# define YY_SYMBOL_PRINT(Title, Kind, Value, Location)
# define YY_STACK_PRINT(Bottom, Top)
# define YY_REDUCE_PRINT(Rule)
#endif /* !YYDEBUG */


/* YYINITDEPTH -- initial size of the parser's stacks.  */
#ifndef YYINITDEPTH
# define YYINITDEPTH 200
#endif

/* YYMAXDEPTH -- maximum size the stacks can grow to (effective only
   if the built-in stack extension method is used).

   Do not make this value too large; the results are undefined if
   YYSTACK_ALLOC_MAXIMUM < YYSTACK_BYTES (YYMAXDEPTH)
   evaluated with infinite-precision integer arithmetic.  */

#ifndef YYMAXDEPTH
# define YYMAXDEPTH 10000
#endif






/*-----------------------------------------------.
| Release the memory associated to this symbol.  |
`-----------------------------------------------*/

static void
yydestruct (const char *yymsg,
            yysymbol_kind_t yykind, YYSTYPE *yyvaluep)
{
  YY_USE (yyvaluep);
  if (!yymsg)
    yymsg = "Deleting";
  YY_SYMBOL_PRINT (yymsg, yykind, yyvaluep, yylocationp);

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  YY_USE (yykind);
  YY_IGNORE_MAYBE_UNINITIALIZED_END
}


/* Lookahead token kind.  */
int yychar;

/* The semantic value of the lookahead symbol.  */
YYSTYPE yylval;
/* Number of syntax errors so far.  */
int yynerrs;




/*----------.
| yyparse.  |
`----------*/

int
yyparse (void)
{
    yy_state_fast_t yystate = 0;
    /* Number of tokens to shift before error messages enabled.  */
    int yyerrstatus = 0;

    /* Refer to the stacks through separate pointers, to allow yyoverflow
       to reallocate them elsewhere.  */

    /* Their size.  */
    YYPTRDIFF_T yystacksize = YYINITDEPTH;

    /* The state stack: array, bottom, top.  */
    yy_state_t yyssa[YYINITDEPTH];
    yy_state_t *yyss = yyssa;
    yy_state_t *yyssp = yyss;

    /* The semantic value stack: array, bottom, top.  */
    YYSTYPE yyvsa[YYINITDEPTH];
    YYSTYPE *yyvs = yyvsa;
    YYSTYPE *yyvsp = yyvs;

  int yyn;
  /* The return value of yyparse.  */
  int yyresult;
  /* Lookahead symbol kind.  */
  yysymbol_kind_t yytoken = YYSYMBOL_YYEMPTY;
  /* The variables used to return semantic value and location from the
     action routines.  */
  YYSTYPE yyval;



#define YYPOPSTACK(N)   (yyvsp -= (N), yyssp -= (N))

  /* The number of symbols on the RHS of the reduced rule.
     Keep to zero when no symbol should be popped.  */
  int yylen = 0;

  YYDPRINTF ((stderr, "Starting parse\n"));

  yychar = YYEMPTY; /* Cause a token to be read.  */

  goto yysetstate;


/*------------------------------------------------------------.
| yynewstate -- push a new state, which is found in yystate.  |
`------------------------------------------------------------*/
yynewstate:
  /* In all cases, when you get here, the value and location stacks
     have just been pushed.  So pushing a state here evens the stacks.  */
  yyssp++;


/*--------------------------------------------------------------------.
| yysetstate -- set current state (the top of the stack) to yystate.  |
`--------------------------------------------------------------------*/
yysetstate:
  YYDPRINTF ((stderr, "Entering state %d\n", yystate));
  YY_ASSERT (0 <= yystate && yystate < YYNSTATES);
  YY_IGNORE_USELESS_CAST_BEGIN
  *yyssp = YY_CAST (yy_state_t, yystate);
  YY_IGNORE_USELESS_CAST_END
  YY_STACK_PRINT (yyss, yyssp);

  if (yyss + yystacksize - 1 <= yyssp)
#if !defined yyoverflow && !defined YYSTACK_RELOCATE
    YYNOMEM;
#else
    {
      /* Get the current used size of the three stacks, in elements.  */
      YYPTRDIFF_T yysize = yyssp - yyss + 1;

# if defined yyoverflow
      {
        /* Give user a chance to reallocate the stack.  Use copies of
           these so that the &'s don't force the real ones into
           memory.  */
        yy_state_t *yyss1 = yyss;
        YYSTYPE *yyvs1 = yyvs;

        /* Each stack pointer address is followed by the size of the
           data in use in that stack, in bytes.  This used to be a
           conditional around just the two extra args, but that might
           be undefined if yyoverflow is a macro.  */
        yyoverflow (YY_("memory exhausted"),
                    &yyss1, yysize * YYSIZEOF (*yyssp),
                    &yyvs1, yysize * YYSIZEOF (*yyvsp),
                    &yystacksize);
        yyss = yyss1;
        yyvs = yyvs1;
      }
# else /* defined YYSTACK_RELOCATE */
      /* Extend the stack our own way.  */
      if (YYMAXDEPTH <= yystacksize)
        YYNOMEM;
      yystacksize *= 2;
      if (YYMAXDEPTH < yystacksize)
        yystacksize = YYMAXDEPTH;

      {
        yy_state_t *yyss1 = yyss;
        union yyalloc *yyptr =
          YY_CAST (union yyalloc *,
                   YYSTACK_ALLOC (YY_CAST (YYSIZE_T, YYSTACK_BYTES (yystacksize))));
        if (! yyptr)
          YYNOMEM;
        YYSTACK_RELOCATE (yyss_alloc, yyss);
        YYSTACK_RELOCATE (yyvs_alloc, yyvs);
#  undef YYSTACK_RELOCATE
        if (yyss1 != yyssa)
          YYSTACK_FREE (yyss1);
      }
# endif

      yyssp = yyss + yysize - 1;
      yyvsp = yyvs + yysize - 1;

      YY_IGNORE_USELESS_CAST_BEGIN
      YYDPRINTF ((stderr, "Stack size increased to %ld\n",
                  YY_CAST (long, yystacksize)));
      YY_IGNORE_USELESS_CAST_END

      if (yyss + yystacksize - 1 <= yyssp)
        YYABORT;
    }
#endif /* !defined yyoverflow && !defined YYSTACK_RELOCATE */


  if (yystate == YYFINAL)
    YYACCEPT;

  goto yybackup;


/*-----------.
| yybackup.  |
`-----------*/
yybackup:
  /* Do appropriate processing given the current state.  Read a
     lookahead token if we need one and don't already have one.  */

  /* First try to decide what to do without reference to lookahead token.  */
  yyn = yypact[yystate];
  if (yypact_value_is_default (yyn))
    goto yydefault;

  /* Not known => get a lookahead token if don't already have one.  */

  /* YYCHAR is either empty, or end-of-input, or a valid lookahead.  */
  if (yychar == YYEMPTY)
    {
      YYDPRINTF ((stderr, "Reading a token\n"));
      yychar = yylex ();
    }

  if (yychar <= YYEOF)
    {
      yychar = YYEOF;
      yytoken = YYSYMBOL_YYEOF;
      YYDPRINTF ((stderr, "Now at end of input.\n"));
    }
  else if (yychar == YYerror)
    {
      /* The scanner already issued an error message, process directly
         to error recovery.  But do not keep the error token as
         lookahead, it is too special and may lead us to an endless
         loop in error recovery. */
      yychar = YYUNDEF;
      yytoken = YYSYMBOL_YYerror;
      goto yyerrlab1;
    }
  else
    {
      yytoken = YYTRANSLATE (yychar);
      YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc);
    }

  /* If the proper action on seeing token YYTOKEN is to reduce or to
     detect an error, take that action.  */
  yyn += yytoken;
  if (yyn < 0 || YYLAST < yyn || yycheck[yyn] != yytoken)
    goto yydefault;
  yyn = yytable[yyn];
  if (yyn <= 0)
    {
      if (yytable_value_is_error (yyn))
        goto yyerrlab;
      yyn = -yyn;
      goto yyreduce;
    }

  /* Count tokens shifted since error; after three, turn off error
     status.  */
  if (yyerrstatus)
    yyerrstatus--;

  /* Shift the lookahead token.  */
  YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc);
  yystate = yyn;
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END

  /* Discard the shifted token.  */
  yychar = YYEMPTY;
  goto yynewstate;


/*-----------------------------------------------------------.
| yydefault -- do the default action for the current state.  |
`-----------------------------------------------------------*/
yydefault:
  yyn = yydefact[yystate];
  if (yyn == 0)
    goto yyerrlab;
  goto yyreduce;


/*-----------------------------.
| yyreduce -- do a reduction.  |
`-----------------------------*/
yyreduce:
  /* yyn is the number of a rule to reduce with.  */
  yylen = yyr2[yyn];

  /* If YYLEN is nonzero, implement the default value of the action:
     '$$ = $1'.

     Otherwise, the following line sets YYVAL to garbage.
     This behavior is undocumented and Bison
     users should not rely upon it.  Assigning to YYVAL
     unconditionally makes the parser a bit smaller, and it avoids a
     GCC warning that YYVAL may be used uninitialized.  */
  yyval = yyvsp[1-yylen];


  YY_REDUCE_PRINT (yyn);
  switch (yyn)
    {
  case 2: /* CompileUnit: FuncDef  */
#line 74 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                      {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_COMPILE_UNIT, (yyvsp[0].node));
        ast_root = (yyval.node);
    }
#line 1307 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 3: /* CompileUnit: Statement  */
#line 78 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_COMPILE_UNIT, (yyvsp[0].node));
        ast_root = (yyval.node);
    }
#line 1316 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 4: /* CompileUnit: CompileUnit FuncDef  */
#line 82 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                          {
        (yyval.node) = insert_ast_node((yyvsp[-1].node), (yyvsp[0].node));
    }
#line 1324 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 5: /* CompileUnit: CompileUnit Statement  */
#line 85 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                            {
        (yyval.node) = insert_ast_node((yyvsp[-1].node), (yyvsp[0].node));
    }
#line 1332 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 6: /* CompileUnit: Decl  */
#line 89 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_COMPILE_UNIT, (yyvsp[0].node));
		// $$ = create_contain_node(ast_operator_type::AST_OP_DECL, $1);
        ast_root = (yyval.node);
	}
#line 1342 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 7: /* CompileUnit: CompileUnit Decl  */
#line 95 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = insert_ast_node((yyvsp[-1].node), (yyvsp[0].node));
	}
#line 1350 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 8: /* FuncDef: T_FUNC T_ID '(' ')' Block  */
#line 101 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                                     {
        (yyval.node) = create_func_def((yyvsp[-3].var_id).lineno, (yyvsp[-3].var_id).id, (yyvsp[0].node), nullptr);
    }
#line 1358 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 9: /* FuncDef: T_FUNC T_ID '(' FuncFormalParams ')' Block  */
#line 104 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                                                 {
        (yyval.node) = create_func_def((yyvsp[-4].var_id).lineno, (yyvsp[-4].var_id).id, (yyvsp[0].node), (yyvsp[-2].node));
    }
#line 1366 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 10: /* FuncDef: T_VOID T_ID '(' ')' Block  */
#line 108 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
        (yyval.node) = create_func_def(BasicType::TYPE_VOID,(yyvsp[-3].var_id).lineno, (yyvsp[-3].var_id).id, (yyvsp[0].node), nullptr);
	}
#line 1374 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 11: /* FuncDef: T_VOID T_ID '(' ')' ';'  */
#line 112 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
        (yyval.node) = create_func_def(BasicType::TYPE_VOID,(yyvsp[-3].var_id).lineno, (yyvsp[-3].var_id).id, nullptr, nullptr);
	}
#line 1382 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 12: /* FuncDef: T_VOID T_ID '(' FuncFormalParams ')' Block  */
#line 116 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
        (yyval.node) = create_func_def(BasicType::TYPE_VOID,(yyvsp[-4].var_id).lineno, (yyvsp[-4].var_id).id, (yyvsp[0].node), (yyvsp[-2].node));
	}
#line 1390 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 13: /* FuncDef: T_VOID T_ID '(' FuncFormalParams ')' ';'  */
#line 120 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
        (yyval.node) = create_func_def(BasicType::TYPE_VOID,(yyvsp[-4].var_id).lineno, (yyvsp[-4].var_id).id, nullptr, (yyvsp[-2].node));
	}
#line 1398 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 14: /* FuncDef: T_INT T_ID '(' ')' Block  */
#line 124 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
        (yyval.node) = create_func_def(BasicType::TYPE_INT,(yyvsp[-3].var_id).lineno, (yyvsp[-3].var_id).id, (yyvsp[0].node), nullptr);
	}
#line 1406 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 15: /* FuncDef: T_INT T_ID '(' FuncFormalParams ')' Block  */
#line 128 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
        (yyval.node) = create_func_def(BasicType::TYPE_INT,(yyvsp[-4].var_id).lineno, (yyvsp[-4].var_id).id, (yyvsp[0].node), (yyvsp[-2].node));
	}
#line 1414 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 16: /* FuncDef: T_INT T_ID '(' ')' ';'  */
#line 132 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
        (yyval.node) = create_func_def(BasicType::TYPE_INT,(yyvsp[-3].var_id).lineno, (yyvsp[-3].var_id).id, nullptr, nullptr);
	}
#line 1422 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 17: /* FuncDef: T_INT T_ID '(' FuncFormalParams ')' ';'  */
#line 136 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
        (yyval.node) = create_func_def(BasicType::TYPE_INT,(yyvsp[-4].var_id).lineno, (yyvsp[-4].var_id).id, nullptr, (yyvsp[-2].node));
	}
#line 1430 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 18: /* FuncFormalParams: FuncFormalParam  */
#line 142 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                                    {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_FUNC_FORMAL_PARAMS, (yyvsp[0].node));
    }
#line 1438 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 19: /* FuncFormalParams: FuncFormalParams ',' FuncFormalParam  */
#line 145 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                                           {
        (yyval.node) = insert_ast_node((yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1446 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 20: /* FuncFormalParam: FuncBasicParam  */
#line 151 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                                  {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1454 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 21: /* FuncBasicParam: T_INT T_ID  */
#line 157 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                            {
        (yyval.node) = create_func_formal_param((yyvsp[0].var_id).lineno, (yyvsp[0].var_id).id);
    }
#line 1462 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 22: /* FuncBasicParam: T_INT T_ID FuncBasicParamArrays  */
#line 161 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		ast_node * id_node = new_ast_leaf_node(var_id_attr{(yyvsp[-1].var_id).id, (yyvsp[-1].var_id).lineno});
		ast_node * return_node = create_contain_node(ast_operator_type::AST_OP_FUNC_ARRAY, id_node);
		update_array_ast_node_info((yyvsp[0].node));
		(yyval.node) = insert_ast_node(return_node, (yyvsp[0].node));
	}
#line 1473 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 23: /* FuncBasicParamArrays: '[' ']'  */
#line 169 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {	
		ast_node *num_node = new_ast_leaf_node(digit_int_attr{0,0});
		ast_node *array_node = new_ast_node(ast_operator_type::AST_OP_ARRAY, nullptr);
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_ARRAY,num_node,array_node,nullptr);

	}
#line 1484 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 24: /* FuncBasicParamArrays: '[' Expr ']'  */
#line 176 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		// ast_node *num_node = new_ast_leaf_node(digit_int_attr{$2.val,$2.lineno});
		ast_node *array_node = new_ast_node(ast_operator_type::AST_OP_ARRAY, nullptr);
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_ARRAY,(yyvsp[-1].node),array_node,nullptr);

	}
#line 1495 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 25: /* FuncBasicParamArrays: FuncBasicParamArrays '[' Expr ']'  */
#line 183 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		// ast_node * num_node = new_ast_leaf_node(digit_int_attr{$3.val, $3.lineno});
		ast_node * array_node = new_ast_node(ast_operator_type::AST_OP_ARRAY,nullptr);
        (yyval.node) = array_insert_ast_node((yyvsp[-3].node),(yyvsp[-1].node),array_node);
	}
#line 1505 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 26: /* Block: '{' '}'  */
#line 191 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                {
        // 语句块没有语句
        (yyval.node) = nullptr;
    }
#line 1514 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 27: /* Block: '{' BlockItemList '}'  */
#line 195 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                            {
        // 语句块含有语句
        (yyval.node) = (yyvsp[-1].node);
    }
#line 1523 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 28: /* BlockItemList: BlockItem  */
#line 202 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                          {
        // 第一个左侧的孩子节点归约成Block父节点，后续语句可不断作为孩子追加到block中
        // 创建一个AST_OP_BLOCK类型的中间节点，孩子为Statement($1)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_BLOCK, (yyvsp[0].node), nullptr);
    }
#line 1533 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 29: /* BlockItemList: BlockItemList BlockItem  */
#line 207 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                               {
        // 采用左递归的文法产生式，可以使得Block节点在上个产生式创建，后续递归追加孩子节点
        // 请注意，不要采用右递归，左递归翻遍孩子的追加
        // BlockItem($2)作为Block($1)的孩子 
        (yyval.node) = insert_ast_node((yyvsp[-1].node), (yyvsp[0].node));
    }
#line 1544 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 30: /* BlockItem: Statement  */
#line 216 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                       {
	
        (yyval.node) = (yyvsp[0].node);
    }
#line 1553 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 31: /* BlockItem: Decl  */
#line 221 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1561 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 32: /* Statement: LVal '=' Expr ';'  */
#line 228 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                              {
        // 归约到Statement时要执行的语义动作程序
        // 赋值语句，不显示值

		// 变量节点
		//ast_node * id_node = new_ast_leaf_node(var_id_attr{$1.id, $1.lineno});

		//free($1.id);

        // 创建一个AST_OP_ASSIGN类型的中间节点，孩子为Id和Expr($3)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_ASSIGN, (yyvsp[-3].node), (yyvsp[-1].node), nullptr);
    }
#line 1578 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 33: /* Statement: Expr ';'  */
#line 240 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
               {
        // Expr归约到Statement时要执行的语义动作程序
        // 表达式语句，不显示表达式的值

        // 创建一个AST_OP_EXPR类型的中间节点，孩子为Expr($1)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_EXPR, (yyvsp[-1].node), nullptr);
    }
#line 1590 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 34: /* Statement: Expr  */
#line 247 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
           {
        // Expr归约到Statement时要执行的语义动作程序
        // 表达式语句，需要显示表达式的值

        // 创建一个AST_OP_EXPR_SHOW类型的中间节点，孩子为Expr($1)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_EXPR_SHOW, (yyvsp[0].node), nullptr);
    }
#line 1602 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 35: /* Statement: ';'  */
#line 255 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = nullptr;
	}
#line 1610 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 36: /* Statement: T_RETURN ';'  */
#line 259 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_RETURN_STATEMENT, nullptr);
	}
#line 1618 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 37: /* Statement: T_RETURN Expr ';'  */
#line 262 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                        {
        // 返回语句
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_RETURN_STATEMENT, (yyvsp[-1].node), nullptr);
    }
#line 1627 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 38: /* Statement: T_IF '(' Cond ')' Statement T_ELSE Statement  */
#line 267 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_IF,(yyvsp[-4].node),(yyvsp[-2].node),(yyvsp[0].node),nullptr);
	}
#line 1635 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 39: /* Statement: T_IF '(' Cond ')' Statement  */
#line 271 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_IF,(yyvsp[-2].node),(yyvsp[0].node),nullptr);
	}
#line 1643 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 40: /* Statement: T_WHILE '(' Cond ')' Statement  */
#line 275 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_WHILE,(yyvsp[-2].node),(yyvsp[0].node),nullptr);
	}
#line 1651 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 41: /* Statement: T_BREAK ';'  */
#line 279 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_leaf_node(BasicType::TYPE_BREAK,0);
	}
#line 1659 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 42: /* Statement: T_CONTINUE ';'  */
#line 283 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_leaf_node(BasicType::TYPE_CONTINUE,0);
	}
#line 1667 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 43: /* Statement: Block  */
#line 287 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1675 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 44: /* Cond: LOrExp  */
#line 293 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		// 
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_COND, (yyvsp[0].node),nullptr);
	}
#line 1684 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 45: /* Expr: LOrExp  */
#line 300 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
              { 
        (yyval.node) = (yyvsp[0].node); 
    }
#line 1692 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 46: /* RelExp: AddExp  */
#line 306 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1700 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 47: /* RelExp: RelExp T_LESS_THAN AddExp  */
#line 310 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		//
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_LESS_THAN, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 1709 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 48: /* RelExp: RelExp T_GREATER_THEN AddExp  */
#line 315 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_GREATER_THAN, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 1717 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 49: /* RelExp: RelExp T_LESS_EQUAL AddExp  */
#line 319 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_LESS_EQUAL, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 1725 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 50: /* RelExp: RelExp T_GREATER_EQUAL AddExp  */
#line 323 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_GREATER_EQUAL, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 1733 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 51: /* EqExp: RelExp  */
#line 329 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1741 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 52: /* EqExp: EqExp T_EQUAL RelExp  */
#line 333 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_EQUAL, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
		
	}
#line 1750 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 53: /* EqExp: EqExp T_NOT_EQUAL RelExp  */
#line 338 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_NOT_EQUAL, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 1758 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 54: /* LAndExp: EqExp  */
#line 343 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1766 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 55: /* LAndExp: LAndExp T_LOGICAL_AND EqExp  */
#line 347 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_LOGICAL_AND, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 1774 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 56: /* LOrExp: LAndExp  */
#line 352 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1782 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 57: /* LOrExp: LOrExp T_LOGICAL_OR LAndExp  */
#line 356 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_LOGICAL_OR, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 1790 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 58: /* Decl: ConstDecl  */
#line 362 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		// $$ = new_ast_node(ast_operator_type::AST_OP_DECL, $1, nullptr);
		(yyval.node) = (yyvsp[0].node);
	}
#line 1799 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 59: /* Decl: VarDecl  */
#line 367 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		// $$ = new_ast_node(ast_operator_type::AST_OP_DECL, $1, nullptr);
		(yyval.node) = (yyvsp[0].node);
	}
#line 1808 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 60: /* ConstExp: AddExp  */
#line 377 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1816 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 61: /* InitVal: Expr  */
#line 383 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = (yyvsp[0].node);
		
	}
#line 1825 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 62: /* InitVal: '{' InitValList '}'  */
#line 388 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = (yyvsp[-1].node);
	}
#line 1833 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 63: /* InitVal: '{' '}'  */
#line 392 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_ARRAY_EMPTY, nullptr);
	}
#line 1841 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 64: /* InitValList: InitVal  */
#line 398 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		// $$ = $1;
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_INIT_VAL_LIST, (yyvsp[0].node));
	}
#line 1850 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 65: /* InitValList: InitValList ',' InitVal  */
#line 403 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
        (yyval.node) = insert_ast_node((yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1858 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 66: /* ConstDecl: T_CONST T_INT ConstDefs ';'  */
#line 409 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		//TYPE_INT = 2
		ast_node * id_node = new_ast_leaf_node(BasicType::TYPE_INT,0);

        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_CONST_DECL, id_node, (yyvsp[-1].node), nullptr);

	}
#line 1870 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 67: /* ConstDefs: ConstDef  */
#line 422 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		//$$ = $1;
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_CONST_DEF, (yyvsp[0].node));

	}
#line 1880 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 68: /* ConstDefs: ConstDefs ',' ConstDef  */
#line 428 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
        (yyval.node) = insert_ast_node((yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1888 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 69: /* ConstInitVal: ConstExp  */
#line 435 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1896 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 70: /* ConstInitVal: '{' InitValList '}'  */
#line 439 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = (yyvsp[-1].node);
	}
#line 1904 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 71: /* ConstInitVal: '{' '}'  */
#line 443 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_ARRAY_EMPTY, nullptr);
	}
#line 1912 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 72: /* ConstDef: T_ID '=' ConstInitVal  */
#line 449 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
        // 赋值语句，不显示值
		// 变量节点
		ast_node * id_node = new_ast_leaf_node(var_id_attr{(yyvsp[-2].var_id).id, (yyvsp[-2].var_id).lineno});

		free((yyvsp[-2].var_id).id);

        // 创建一个AST_OP_ConstDef类型的中间节点，孩子为Id和ConstInitVal($3)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_ASSIGN, id_node, (yyvsp[0].node), nullptr);

	}
#line 1928 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 73: /* ConstDef: T_ID ArrayLists '=' ConstInitVal  */
#line 468 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		ast_node * id_node = new_ast_leaf_node(var_id_attr{(yyvsp[-3].var_id).id, (yyvsp[-3].var_id).lineno});
		update_array_ast_node_info((yyvsp[-2].node));
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_ARRAY_DEF, id_node,(yyvsp[-2].node),(yyvsp[0].node), nullptr);
	}
#line 1938 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 74: /* VarDef: T_ID  */
#line 477 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		ast_node * id_node = new_ast_leaf_node(var_id_attr{(yyvsp[0].var_id).id, (yyvsp[0].var_id).lineno});
		
		// $$ = new_ast_node(ast_operator_type::AST_OP_VAR_DEF, $1, nullptr);
		(yyval.node) = id_node;
	}
#line 1949 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 75: /* VarDef: T_ID '=' InitVal  */
#line 484 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		// 赋值语句，不显示值
		// 变量节点
		ast_node * id_node = new_ast_leaf_node(var_id_attr{(yyvsp[-2].var_id).id, (yyvsp[-2].var_id).lineno});

		free((yyvsp[-2].var_id).id);

        // 创建一个AST_OP_ConstDef类型的中间节点，孩子为Id和ConstInitVal($3)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_ASSIGN, id_node, (yyvsp[0].node), nullptr);
	}
#line 1964 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 76: /* VarDef: T_ID ArrayLists  */
#line 495 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		// ?
		ast_node * id_node = new_ast_leaf_node(var_id_attr{(yyvsp[-1].var_id).id, (yyvsp[-1].var_id).lineno});
		update_array_ast_node_info((yyvsp[0].node));
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_ARRAY_DEF, id_node,(yyvsp[0].node), nullptr);
	}
#line 1975 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 77: /* VarDef: T_ID ArrayLists '=' InitVal  */
#line 502 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		ast_node * id_node = new_ast_leaf_node(var_id_attr{(yyvsp[-3].var_id).id, (yyvsp[-3].var_id).lineno});
		update_array_ast_node_info((yyvsp[-2].node));
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_ARRAY_DEF, id_node,(yyvsp[-2].node),(yyvsp[0].node), nullptr);
	}
#line 1985 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 78: /* ArrayLists: '[' ConstExp ']'  */
#line 510 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		
        // ast_node * num_node = new_ast_leaf_node(digit_int_attr{$2.val, $2.lineno});
		ast_node * array_node = new_ast_node(ast_operator_type::AST_OP_ARRAY,nullptr);
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_ARRAY,(yyvsp[-1].node),array_node,nullptr);
	}
#line 1996 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 79: /* ArrayLists: ArrayLists '[' ConstExp ']'  */
#line 517 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
        // ast_node * num_node = new_ast_leaf_node(digit_int_attr{$3.val, $3.lineno});
		ast_node * array_node = new_ast_node(ast_operator_type::AST_OP_ARRAY,nullptr);

        (yyval.node) = array_insert_ast_node((yyvsp[-3].node),(yyvsp[-1].node),array_node);

	}
#line 2008 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 80: /* VarDecl: T_INT VarDefs ';'  */
#line 527 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		//TYPE_INT = 2
		ast_node * id_node = new_ast_leaf_node(BasicType::TYPE_INT,0);

        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_VAR_DECL, id_node, (yyvsp[-1].node), nullptr);
	}
#line 2019 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 81: /* VarDefs: VarDef  */
#line 535 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		// $$ = $1;
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_VAR_DEF, (yyvsp[0].node));
	}
#line 2028 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 82: /* VarDefs: VarDefs ',' VarDef  */
#line 540 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {	
        (yyval.node) = insert_ast_node((yyvsp[-2].node), (yyvsp[0].node));
	}
#line 2036 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 83: /* AddExp: AddExp T_ADD MulExp  */
#line 545 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                             {
        /* Expr = Expr + Term */

        // 创建一个AST_OP_ADD类型的中间节点，孩子为Expr($1)和Term($3)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_ADD, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
    }
#line 2047 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 84: /* AddExp: AddExp T_SUB MulExp  */
#line 551 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                          {
        /* Expr = Expr + Term */

        // 创建一个AST_OP_ADD类型的中间节点，孩子为Expr($1)和Term($3)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_SUB, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
    }
#line 2058 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 85: /* AddExp: MulExp  */
#line 557 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
               {
		(yyval.node) = (yyvsp[0].node);
	}
#line 2066 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 86: /* MulExp: MulExp T_TIMES UnaryExp  */
#line 562 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_TIMES,(yyvsp[-2].node),(yyvsp[0].node),nullptr);
	}
#line 2074 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 87: /* MulExp: MulExp T_DIV UnaryExp  */
#line 566 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_DIV,(yyvsp[-2].node),(yyvsp[0].node),nullptr);
	}
#line 2082 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 88: /* MulExp: MulExp T_MOD UnaryExp  */
#line 570 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_MOD,(yyvsp[-2].node),(yyvsp[0].node),nullptr);
	}
#line 2090 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 89: /* MulExp: UnaryExp  */
#line 574 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		/* Expr = Term */
        (yyval.node) = (yyvsp[0].node);
	}
#line 2099 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 90: /* UnaryExp: PrimaryExp  */
#line 595 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                      {
        (yyval.node) = (yyvsp[0].node);
    }
#line 2107 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 91: /* UnaryExp: T_ID '(' ')'  */
#line 598 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                   {
        // 用户自定义的不含实参的函数调用
        (yyval.node) = create_func_call((yyvsp[-2].var_id).lineno, (yyvsp[-2].var_id).id, nullptr);
    }
#line 2116 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 92: /* UnaryExp: T_ID '(' RealParamList ')'  */
#line 602 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                                 {
        // 用户自定义的含有实参的参数调用
        (yyval.node) = create_func_call((yyvsp[-3].var_id).lineno, (yyvsp[-3].var_id).id, (yyvsp[-1].node));
    }
#line 2125 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 93: /* UnaryExp: T_ADD UnaryExp  */
#line 607 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_POSITIVE,(yyvsp[0].node),nullptr);
	}
#line 2133 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 94: /* UnaryExp: T_SUB UnaryExp  */
#line 611 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_NEGATIVE,(yyvsp[0].node),nullptr);
		
	}
#line 2142 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 95: /* UnaryExp: T_NOT UnaryExp  */
#line 616 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
        //$$ = new_ast_node(ast_operator_type::AST_OP_EXPR_SHOW, $1, nullptr);
		// 
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_NOT,(yyvsp[0].node),nullptr);
	}
#line 2152 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 96: /* PrimaryExp: '(' Expr ')'  */
#line 622 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                           {
        /* PrimaryExp = Expr */
        (yyval.node) = (yyvsp[-1].node);
    }
#line 2161 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 97: /* PrimaryExp: T_DIGIT  */
#line 626 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
              {
        // 无符号整数识别

        // 终结符作为抽象语法树的叶子节点进行创建
        (yyval.node) = new_ast_leaf_node(digit_int_attr{(yyvsp[0].integer_num).val, (yyvsp[0].integer_num).lineno});
    }
#line 2172 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 98: /* PrimaryExp: LVal  */
#line 632 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
            {
        // 左值
        (yyval.node) = (yyvsp[0].node);
    }
#line 2181 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 99: /* LVal: T_ID  */
#line 639 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
            {
        // 终结符作为抽象语法树的叶子节点进行创建
        (yyval.node) = new_ast_leaf_node(var_id_attr{(yyvsp[0].var_id).id, (yyvsp[0].var_id).lineno});

		// 对于字符型字面量的字符串空间需要释放，因词法用到了strdup进行了字符串复制
		free((yyvsp[0].var_id).id);
    }
#line 2193 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 100: /* LVal: T_ID LValueList  */
#line 647 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		ast_node *id_node = new_ast_leaf_node(var_id_attr{(yyvsp[-1].var_id).id, (yyvsp[-1].var_id).lineno});
        ast_node *return_node = create_contain_node(ast_operator_type::AST_OP_ARRAY_VISIT, id_node);
		(yyval.node) = insert_ast_node(return_node, (yyvsp[0].node));
	}
#line 2203 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 101: /* LValueList: '[' Expr ']'  */
#line 654 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		// ast_node *id_node = new_ast_leaf_node(var_id_attr{$2.id, $2.lineno});
		// ast_node * info_node = new_info_node(ast_operator_type::AST_OP_INFO_ARRAY_VISIT,$2.val);
		// ast_node * info_node = new_ast_node(ast_operator_type::AST_OP_INFO_ARRAY_VISIT,$2,nullptr);
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_INFO_ARRAY_VISIT, (yyvsp[-1].node));

	}
#line 2215 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 102: /* LValueList: LValueList '[' Expr ']'  */
#line 662 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		// ast_node * info_node = new_info_node(ast_operator_type::AST_OP_INFO_ARRAY_VISIT,$3.val);
		// ast_node * info_node = new_ast_node(ast_operator_type::AST_OP_INFO_ARRAY_VISIT,$3,nullptr);
		(yyval.node) = insert_ast_node((yyvsp[-3].node), (yyvsp[-1].node));
	}
#line 2225 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 103: /* RealParamList: Expr  */
#line 671 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                     {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_FUNC_REAL_PARAMS, (yyvsp[0].node));
    }
#line 2233 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 104: /* RealParamList: RealParamList ',' Expr  */
#line 674 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                             {
        (yyval.node) = insert_ast_node((yyvsp[-2].node), (yyvsp[0].node));
    }
#line 2241 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;


#line 2245 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"

      default: break;
    }
  /* User semantic actions sometimes alter yychar, and that requires
     that yytoken be updated with the new translation.  We take the
     approach of translating immediately before every use of yytoken.
     One alternative is translating here after every semantic action,
     but that translation would be missed if the semantic action invokes
     YYABORT, YYACCEPT, or YYERROR immediately after altering yychar or
     if it invokes YYBACKUP.  In the case of YYABORT or YYACCEPT, an
     incorrect destructor might then be invoked immediately.  In the
     case of YYERROR or YYBACKUP, subsequent parser actions might lead
     to an incorrect destructor call or verbose syntax error message
     before the lookahead is translated.  */
  YY_SYMBOL_PRINT ("-> $$ =", YY_CAST (yysymbol_kind_t, yyr1[yyn]), &yyval, &yyloc);

  YYPOPSTACK (yylen);
  yylen = 0;

  *++yyvsp = yyval;

  /* Now 'shift' the result of the reduction.  Determine what state
     that goes to, based on the state we popped back to and the rule
     number reduced by.  */
  {
    const int yylhs = yyr1[yyn] - YYNTOKENS;
    const int yyi = yypgoto[yylhs] + *yyssp;
    yystate = (0 <= yyi && yyi <= YYLAST && yycheck[yyi] == *yyssp
               ? yytable[yyi]
               : yydefgoto[yylhs]);
  }

  goto yynewstate;


/*--------------------------------------.
| yyerrlab -- here on detecting error.  |
`--------------------------------------*/
yyerrlab:
  /* Make sure we have latest lookahead translation.  See comments at
     user semantic actions for why this is necessary.  */
  yytoken = yychar == YYEMPTY ? YYSYMBOL_YYEMPTY : YYTRANSLATE (yychar);
  /* If not already recovering from an error, report this error.  */
  if (!yyerrstatus)
    {
      ++yynerrs;
      yyerror (YY_("syntax error"));
    }

  if (yyerrstatus == 3)
    {
      /* If just tried and failed to reuse lookahead token after an
         error, discard it.  */

      if (yychar <= YYEOF)
        {
          /* Return failure if at end of input.  */
          if (yychar == YYEOF)
            YYABORT;
        }
      else
        {
          yydestruct ("Error: discarding",
                      yytoken, &yylval);
          yychar = YYEMPTY;
        }
    }

  /* Else will try to reuse lookahead token after shifting the error
     token.  */
  goto yyerrlab1;


/*---------------------------------------------------.
| yyerrorlab -- error raised explicitly by YYERROR.  |
`---------------------------------------------------*/
yyerrorlab:
  /* Pacify compilers when the user code never invokes YYERROR and the
     label yyerrorlab therefore never appears in user code.  */
  if (0)
    YYERROR;
  ++yynerrs;

  /* Do not reclaim the symbols of the rule whose action triggered
     this YYERROR.  */
  YYPOPSTACK (yylen);
  yylen = 0;
  YY_STACK_PRINT (yyss, yyssp);
  yystate = *yyssp;
  goto yyerrlab1;


/*-------------------------------------------------------------.
| yyerrlab1 -- common code for both syntax error and YYERROR.  |
`-------------------------------------------------------------*/
yyerrlab1:
  yyerrstatus = 3;      /* Each real token shifted decrements this.  */

  /* Pop stack until we find a state that shifts the error token.  */
  for (;;)
    {
      yyn = yypact[yystate];
      if (!yypact_value_is_default (yyn))
        {
          yyn += YYSYMBOL_YYerror;
          if (0 <= yyn && yyn <= YYLAST && yycheck[yyn] == YYSYMBOL_YYerror)
            {
              yyn = yytable[yyn];
              if (0 < yyn)
                break;
            }
        }

      /* Pop the current state because it cannot handle the error token.  */
      if (yyssp == yyss)
        YYABORT;


      yydestruct ("Error: popping",
                  YY_ACCESSING_SYMBOL (yystate), yyvsp);
      YYPOPSTACK (1);
      yystate = *yyssp;
      YY_STACK_PRINT (yyss, yyssp);
    }

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END


  /* Shift the error token.  */
  YY_SYMBOL_PRINT ("Shifting", YY_ACCESSING_SYMBOL (yyn), yyvsp, yylsp);

  yystate = yyn;
  goto yynewstate;


/*-------------------------------------.
| yyacceptlab -- YYACCEPT comes here.  |
`-------------------------------------*/
yyacceptlab:
  yyresult = 0;
  goto yyreturnlab;


/*-----------------------------------.
| yyabortlab -- YYABORT comes here.  |
`-----------------------------------*/
yyabortlab:
  yyresult = 1;
  goto yyreturnlab;


/*-----------------------------------------------------------.
| yyexhaustedlab -- YYNOMEM (memory exhaustion) comes here.  |
`-----------------------------------------------------------*/
yyexhaustedlab:
  yyerror (YY_("memory exhausted"));
  yyresult = 2;
  goto yyreturnlab;


/*----------------------------------------------------------.
| yyreturnlab -- parsing is finished, clean up and return.  |
`----------------------------------------------------------*/
yyreturnlab:
  if (yychar != YYEMPTY)
    {
      /* Make sure we have latest lookahead translation.  See comments at
         user semantic actions for why this is necessary.  */
      yytoken = YYTRANSLATE (yychar);
      yydestruct ("Cleanup: discarding lookahead",
                  yytoken, &yylval);
    }
  /* Do not reclaim the symbols of the rule whose action triggered
     this YYABORT or YYACCEPT.  */
  YYPOPSTACK (yylen);
  YY_STACK_PRINT (yyss, yyssp);
  while (yyssp != yyss)
    {
      yydestruct ("Cleanup: popping",
                  YY_ACCESSING_SYMBOL (+*yyssp), yyvsp);
      YYPOPSTACK (1);
    }
#ifndef yyoverflow
  if (yyss != yyssa)
    YYSTACK_FREE (yyss);
#endif

  return yyresult;
}

#line 678 "/home/zhao/calculator/frontend/flexbison/Calculator.y"


// 语法识别错误要调用函数的定义
void yyerror(char * msg)
{
    printf("Line %d: %s\n", yylineno, msg);
}
