/* A Bison parser, made by GNU Bison 3.8.2.  */

/* Bison implementation for Yacc-like parsers in C

   Copyright (C) 1984, 1989-1990, 2000-2015, 2018-2021 Free Software Foundation,
   Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* C LALR(1) parser skeleton written by Richard Stallman, by
   simplifying the original so-called "semantic" parser.  */

/* DO NOT RELY ON FEATURES THAT ARE NOT DOCUMENTED in the manual,
   especially those whose name start with YY_ or yy_.  They are
   private implementation details that can be changed or removed.  */

/* All symbols defined below should begin with yy or YY, to avoid
   infringing on user name space.  This should be done even for local
   variables, as they might otherwise be expanded by user macros.
   There are some unavoidable exceptions within include files to
   define necessary library symbols; they are noted "INFRINGES ON
   USER NAME SPACE" below.  */

/* Identify Bison output, and Bison version.  */
#define YYBISON 30802

/* Bison version string.  */
#define YYBISON_VERSION "3.8.2"

/* Skeleton name.  */
#define YYSKELETON_NAME "yacc.c"

/* Pure parsers.  */
#define YYPURE 0

/* Push parsers.  */
#define YYPUSH 0

/* Pull parsers.  */
#define YYPULL 1




/* First part of user prologue.  */
#line 1 "/home/zhao/calculator/frontend/flexbison/Calculator.y"

#include <cstdio>
#include <cstring>
#include "../../common/ValueType.h"
// 词法分析头文件
#include "FlexLexer.h"

// bison生成的头文件
#include "BisonParser.h"

// 抽象语法树函数定义原型头文件
#include "AST.h"

// LR分析失败时所调用函数的原型声明
void yyerror(char * msg);


#line 89 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"

# ifndef YY_CAST
#  ifdef __cplusplus
#   define YY_CAST(Type, Val) static_cast<Type> (Val)
#   define YY_REINTERPRET_CAST(Type, Val) reinterpret_cast<Type> (Val)
#  else
#   define YY_CAST(Type, Val) ((Type) (Val))
#   define YY_REINTERPRET_CAST(Type, Val) ((Type) (Val))
#  endif
# endif
# ifndef YY_NULLPTR
#  if defined __cplusplus
#   if 201103L <= __cplusplus
#    define YY_NULLPTR nullptr
#   else
#    define YY_NULLPTR 0
#   endif
#  else
#   define YY_NULLPTR ((void*)0)
#  endif
# endif

#include "CalculatorBison.h"
/* Symbol kind.  */
enum yysymbol_kind_t
{
  YYSYMBOL_YYEMPTY = -2,
  YYSYMBOL_YYEOF = 0,                      /* "end of file"  */
  YYSYMBOL_YYerror = 1,                    /* error  */
  YYSYMBOL_YYUNDEF = 2,                    /* "invalid token"  */
  YYSYMBOL_T_DIGIT = 3,                    /* T_DIGIT  */
  YYSYMBOL_T_ID = 4,                       /* T_ID  */
  YYSYMBOL_T_FUNC = 5,                     /* T_FUNC  */
  YYSYMBOL_T_RETURN = 6,                   /* T_RETURN  */
  YYSYMBOL_T_MAIN = 7,                     /* T_MAIN  */
  YYSYMBOL_T_IF = 8,                       /* T_IF  */
  YYSYMBOL_T_ELSE = 9,                     /* T_ELSE  */
  YYSYMBOL_T_WHILE = 10,                   /* T_WHILE  */
  YYSYMBOL_T_CONST = 11,                   /* T_CONST  */
  YYSYMBOL_T_VOID = 12,                    /* T_VOID  */
  YYSYMBOL_T_CONTINUE = 13,                /* T_CONTINUE  */
  YYSYMBOL_T_BREAK = 14,                   /* T_BREAK  */
  YYSYMBOL_T_INT = 15,                     /* T_INT  */
  YYSYMBOL_T_ADD = 16,                     /* T_ADD  */
  YYSYMBOL_T_SUB = 17,                     /* T_SUB  */
  YYSYMBOL_T_TIMES = 18,                   /* T_TIMES  */
  YYSYMBOL_T_DIV = 19,                     /* T_DIV  */
  YYSYMBOL_T_MOD = 20,                     /* T_MOD  */
  YYSYMBOL_T_EQUAL = 21,                   /* T_EQUAL  */
  YYSYMBOL_T_NOT_EQUAL = 22,               /* T_NOT_EQUAL  */
  YYSYMBOL_T_LESS_THAN = 23,               /* T_LESS_THAN  */
  YYSYMBOL_T_GREATER_THEN = 24,            /* T_GREATER_THEN  */
  YYSYMBOL_T_LESS_EQUAL = 25,              /* T_LESS_EQUAL  */
  YYSYMBOL_T_GREATER_EQUAL = 26,           /* T_GREATER_EQUAL  */
  YYSYMBOL_T_LOGICAL_AND = 27,             /* T_LOGICAL_AND  */
  YYSYMBOL_T_LOGICAL_OR = 28,              /* T_LOGICAL_OR  */
  YYSYMBOL_T_NOT = 29,                     /* T_NOT  */
  YYSYMBOL_30_ = 30,                       /* '('  */
  YYSYMBOL_31_ = 31,                       /* ')'  */
  YYSYMBOL_32_ = 32,                       /* ','  */
  YYSYMBOL_33_ = 33,                       /* '['  */
  YYSYMBOL_34_ = 34,                       /* ']'  */
  YYSYMBOL_35_ = 35,                       /* '{'  */
  YYSYMBOL_36_ = 36,                       /* '}'  */
  YYSYMBOL_37_ = 37,                       /* '='  */
  YYSYMBOL_38_ = 38,                       /* ';'  */
  YYSYMBOL_YYACCEPT = 39,                  /* $accept  */
  YYSYMBOL_CompileUnit = 40,               /* CompileUnit  */
  YYSYMBOL_FuncDef = 41,                   /* FuncDef  */
  YYSYMBOL_FuncFormalParams = 42,          /* FuncFormalParams  */
  YYSYMBOL_FuncFormalParam = 43,           /* FuncFormalParam  */
  YYSYMBOL_FuncBasicParam = 44,            /* FuncBasicParam  */
  YYSYMBOL_FuncBasicParamArrays = 45,      /* FuncBasicParamArrays  */
  YYSYMBOL_Block = 46,                     /* Block  */
  YYSYMBOL_BlockItemList = 47,             /* BlockItemList  */
  YYSYMBOL_BlockItem = 48,                 /* BlockItem  */
  YYSYMBOL_Statement = 49,                 /* Statement  */
  YYSYMBOL_Cond = 50,                      /* Cond  */
  YYSYMBOL_Expr = 51,                      /* Expr  */
  YYSYMBOL_RelExp = 52,                    /* RelExp  */
  YYSYMBOL_EqExp = 53,                     /* EqExp  */
  YYSYMBOL_LAndExp = 54,                   /* LAndExp  */
  YYSYMBOL_LOrExp = 55,                    /* LOrExp  */
  YYSYMBOL_Decl = 56,                      /* Decl  */
  YYSYMBOL_ConstExp = 57,                  /* ConstExp  */
  YYSYMBOL_InitVal = 58,                   /* InitVal  */
  YYSYMBOL_InitValList = 59,               /* InitValList  */
  YYSYMBOL_ConstDecl = 60,                 /* ConstDecl  */
  YYSYMBOL_ConstDefs = 61,                 /* ConstDefs  */
  YYSYMBOL_ConstInitVal = 62,              /* ConstInitVal  */
  YYSYMBOL_ConstDef = 63,                  /* ConstDef  */
  YYSYMBOL_VarDef = 64,                    /* VarDef  */
  YYSYMBOL_ArrayLists = 65,                /* ArrayLists  */
  YYSYMBOL_VarDecl = 66,                   /* VarDecl  */
  YYSYMBOL_VarDefs = 67,                   /* VarDefs  */
  YYSYMBOL_AddExp = 68,                    /* AddExp  */
  YYSYMBOL_MulExp = 69,                    /* MulExp  */
  YYSYMBOL_UnaryExp = 70,                  /* UnaryExp  */
  YYSYMBOL_PrimaryExp = 71,                /* PrimaryExp  */
  YYSYMBOL_LVal = 72,                      /* LVal  */
  YYSYMBOL_LValueList = 73,                /* LValueList  */
  YYSYMBOL_RealParamList = 74              /* RealParamList  */
};
typedef enum yysymbol_kind_t yysymbol_kind_t;




#ifdef short
# undef short
#endif

/* On compilers that do not define __PTRDIFF_MAX__ etc., make sure
   <limits.h> and (if available) <stdint.h> are included
   so that the code can choose integer types of a good width.  */

#ifndef __PTRDIFF_MAX__
# include <limits.h> /* INFRINGES ON USER NAME SPACE */
# if defined __STDC_VERSION__ && 199901 <= __STDC_VERSION__
#  include <stdint.h> /* INFRINGES ON USER NAME SPACE */
#  define YY_STDINT_H
# endif
#endif

/* Narrow types that promote to a signed type and that can represent a
   signed or unsigned integer of at least N bits.  In tables they can
   save space and decrease cache pressure.  Promoting to a signed type
   helps avoid bugs in integer arithmetic.  */

#ifdef __INT_LEAST8_MAX__
typedef __INT_LEAST8_TYPE__ yytype_int8;
#elif defined YY_STDINT_H
typedef int_least8_t yytype_int8;
#else
typedef signed char yytype_int8;
#endif

#ifdef __INT_LEAST16_MAX__
typedef __INT_LEAST16_TYPE__ yytype_int16;
#elif defined YY_STDINT_H
typedef int_least16_t yytype_int16;
#else
typedef short yytype_int16;
#endif

/* Work around bug in HP-UX 11.23, which defines these macros
   incorrectly for preprocessor constants.  This workaround can likely
   be removed in 2023, as HPE has promised support for HP-UX 11.23
   (aka HP-UX 11i v2) only through the end of 2022; see Table 2 of
   <https://h20195.www2.hpe.com/V2/getpdf.aspx/4AA4-7673ENW.pdf>.  */
#ifdef __hpux
# undef UINT_LEAST8_MAX
# undef UINT_LEAST16_MAX
# define UINT_LEAST8_MAX 255
# define UINT_LEAST16_MAX 65535
#endif

#if defined __UINT_LEAST8_MAX__ && __UINT_LEAST8_MAX__ <= __INT_MAX__
typedef __UINT_LEAST8_TYPE__ yytype_uint8;
#elif (!defined __UINT_LEAST8_MAX__ && defined YY_STDINT_H \
       && UINT_LEAST8_MAX <= INT_MAX)
typedef uint_least8_t yytype_uint8;
#elif !defined __UINT_LEAST8_MAX__ && UCHAR_MAX <= INT_MAX
typedef unsigned char yytype_uint8;
#else
typedef short yytype_uint8;
#endif

#if defined __UINT_LEAST16_MAX__ && __UINT_LEAST16_MAX__ <= __INT_MAX__
typedef __UINT_LEAST16_TYPE__ yytype_uint16;
#elif (!defined __UINT_LEAST16_MAX__ && defined YY_STDINT_H \
       && UINT_LEAST16_MAX <= INT_MAX)
typedef uint_least16_t yytype_uint16;
#elif !defined __UINT_LEAST16_MAX__ && USHRT_MAX <= INT_MAX
typedef unsigned short yytype_uint16;
#else
typedef int yytype_uint16;
#endif

#ifndef YYPTRDIFF_T
# if defined __PTRDIFF_TYPE__ && defined __PTRDIFF_MAX__
#  define YYPTRDIFF_T __PTRDIFF_TYPE__
#  define YYPTRDIFF_MAXIMUM __PTRDIFF_MAX__
# elif defined PTRDIFF_MAX
#  ifndef ptrdiff_t
#   include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  endif
#  define YYPTRDIFF_T ptrdiff_t
#  define YYPTRDIFF_MAXIMUM PTRDIFF_MAX
# else
#  define YYPTRDIFF_T long
#  define YYPTRDIFF_MAXIMUM LONG_MAX
# endif
#endif

#ifndef YYSIZE_T
# ifdef __SIZE_TYPE__
#  define YYSIZE_T __SIZE_TYPE__
# elif defined size_t
#  define YYSIZE_T size_t
# elif defined __STDC_VERSION__ && 199901 <= __STDC_VERSION__
#  include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  define YYSIZE_T size_t
# else
#  define YYSIZE_T unsigned
# endif
#endif

#define YYSIZE_MAXIMUM                                  \
  YY_CAST (YYPTRDIFF_T,                                 \
           (YYPTRDIFF_MAXIMUM < YY_CAST (YYSIZE_T, -1)  \
            ? YYPTRDIFF_MAXIMUM                         \
            : YY_CAST (YYSIZE_T, -1)))

#define YYSIZEOF(X) YY_CAST (YYPTRDIFF_T, sizeof (X))


/* Stored state numbers (used for stacks). */
typedef yytype_uint8 yy_state_t;

/* State numbers in computations.  */
typedef int yy_state_fast_t;

#ifndef YY_
# if defined YYENABLE_NLS && YYENABLE_NLS
#  if ENABLE_NLS
#   include <libintl.h> /* INFRINGES ON USER NAME SPACE */
#   define YY_(Msgid) dgettext ("bison-runtime", Msgid)
#  endif
# endif
# ifndef YY_
#  define YY_(Msgid) Msgid
# endif
#endif


#ifndef YY_ATTRIBUTE_PURE
# if defined __GNUC__ && 2 < __GNUC__ + (96 <= __GNUC_MINOR__)
#  define YY_ATTRIBUTE_PURE __attribute__ ((__pure__))
# else
#  define YY_ATTRIBUTE_PURE
# endif
#endif

#ifndef YY_ATTRIBUTE_UNUSED
# if defined __GNUC__ && 2 < __GNUC__ + (7 <= __GNUC_MINOR__)
#  define YY_ATTRIBUTE_UNUSED __attribute__ ((__unused__))
# else
#  define YY_ATTRIBUTE_UNUSED
# endif
#endif

/* Suppress unused-variable warnings by "using" E.  */
#if ! defined lint || defined __GNUC__
# define YY_USE(E) ((void) (E))
#else
# define YY_USE(E) /* empty */
#endif

/* Suppress an incorrect diagnostic about yylval being uninitialized.  */
#if defined __GNUC__ && ! defined __ICC && 406 <= __GNUC__ * 100 + __GNUC_MINOR__
# if __GNUC__ * 100 + __GNUC_MINOR__ < 407
#  define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN                           \
    _Pragma ("GCC diagnostic push")                                     \
    _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"")
# else
#  define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN                           \
    _Pragma ("GCC diagnostic push")                                     \
    _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"")              \
    _Pragma ("GCC diagnostic ignored \"-Wmaybe-uninitialized\"")
# endif
# define YY_IGNORE_MAYBE_UNINITIALIZED_END      \
    _Pragma ("GCC diagnostic pop")
#else
# define YY_INITIAL_VALUE(Value) Value
#endif
#ifndef YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_END
#endif
#ifndef YY_INITIAL_VALUE
# define YY_INITIAL_VALUE(Value) /* Nothing. */
#endif

#if defined __cplusplus && defined __GNUC__ && ! defined __ICC && 6 <= __GNUC__
# define YY_IGNORE_USELESS_CAST_BEGIN                          \
    _Pragma ("GCC diagnostic push")                            \
    _Pragma ("GCC diagnostic ignored \"-Wuseless-cast\"")
# define YY_IGNORE_USELESS_CAST_END            \
    _Pragma ("GCC diagnostic pop")
#endif
#ifndef YY_IGNORE_USELESS_CAST_BEGIN
# define YY_IGNORE_USELESS_CAST_BEGIN
# define YY_IGNORE_USELESS_CAST_END
#endif


#define YY_ASSERT(E) ((void) (0 && (E)))

#if !defined yyoverflow

/* The parser invokes alloca or malloc; define the necessary symbols.  */

# ifdef YYSTACK_USE_ALLOCA
#  if YYSTACK_USE_ALLOCA
#   ifdef __GNUC__
#    define YYSTACK_ALLOC __builtin_alloca
#   elif defined __BUILTIN_VA_ARG_INCR
#    include <alloca.h> /* INFRINGES ON USER NAME SPACE */
#   elif defined _AIX
#    define YYSTACK_ALLOC __alloca
#   elif defined _MSC_VER
#    include <malloc.h> /* INFRINGES ON USER NAME SPACE */
#    define alloca _alloca
#   else
#    define YYSTACK_ALLOC alloca
#    if ! defined _ALLOCA_H && ! defined EXIT_SUCCESS
#     include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
      /* Use EXIT_SUCCESS as a witness for stdlib.h.  */
#     ifndef EXIT_SUCCESS
#      define EXIT_SUCCESS 0
#     endif
#    endif
#   endif
#  endif
# endif

# ifdef YYSTACK_ALLOC
   /* Pacify GCC's 'empty if-body' warning.  */
#  define YYSTACK_FREE(Ptr) do { /* empty */; } while (0)
#  ifndef YYSTACK_ALLOC_MAXIMUM
    /* The OS might guarantee only one guard page at the bottom of the stack,
       and a page size can be as small as 4096 bytes.  So we cannot safely
       invoke alloca (N) if N exceeds 4096.  Use a slightly smaller number
       to allow for a few compiler-allocated temporary stack slots.  */
#   define YYSTACK_ALLOC_MAXIMUM 4032 /* reasonable circa 2006 */
#  endif
# else
#  define YYSTACK_ALLOC YYMALLOC
#  define YYSTACK_FREE YYFREE
#  ifndef YYSTACK_ALLOC_MAXIMUM
#   define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#  endif
#  if (defined __cplusplus && ! defined EXIT_SUCCESS \
       && ! ((defined YYMALLOC || defined malloc) \
             && (defined YYFREE || defined free)))
#   include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
#   ifndef EXIT_SUCCESS
#    define EXIT_SUCCESS 0
#   endif
#  endif
#  ifndef YYMALLOC
#   define YYMALLOC malloc
#   if ! defined malloc && ! defined EXIT_SUCCESS
void *malloc (YYSIZE_T); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
#  ifndef YYFREE
#   define YYFREE free
#   if ! defined free && ! defined EXIT_SUCCESS
void free (void *); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
# endif
#endif /* !defined yyoverflow */

#if (! defined yyoverflow \
     && (! defined __cplusplus \
         || (defined YYSTYPE_IS_TRIVIAL && YYSTYPE_IS_TRIVIAL)))

/* A type that is properly aligned for any stack member.  */
union yyalloc
{
  yy_state_t yyss_alloc;
  YYSTYPE yyvs_alloc;
};

/* The size of the maximum gap between one aligned stack and the next.  */
# define YYSTACK_GAP_MAXIMUM (YYSIZEOF (union yyalloc) - 1)

/* The size of an array large to enough to hold all stacks, each with
   N elements.  */
# define YYSTACK_BYTES(N) \
     ((N) * (YYSIZEOF (yy_state_t) + YYSIZEOF (YYSTYPE)) \
      + YYSTACK_GAP_MAXIMUM)

# define YYCOPY_NEEDED 1

/* Relocate STACK from its old location to the new one.  The
   local variables YYSIZE and YYSTACKSIZE give the old and new number of
   elements in the stack, and YYPTR gives the new location of the
   stack.  Advance YYPTR to a properly aligned location for the next
   stack.  */
# define YYSTACK_RELOCATE(Stack_alloc, Stack)                           \
    do                                                                  \
      {                                                                 \
        YYPTRDIFF_T yynewbytes;                                         \
        YYCOPY (&yyptr->Stack_alloc, Stack, yysize);                    \
        Stack = &yyptr->Stack_alloc;                                    \
        yynewbytes = yystacksize * YYSIZEOF (*Stack) + YYSTACK_GAP_MAXIMUM; \
        yyptr += yynewbytes / YYSIZEOF (*yyptr);                        \
      }                                                                 \
    while (0)

#endif

#if defined YYCOPY_NEEDED && YYCOPY_NEEDED
/* Copy COUNT objects from SRC to DST.  The source and destination do
   not overlap.  */
# ifndef YYCOPY
#  if defined __GNUC__ && 1 < __GNUC__
#   define YYCOPY(Dst, Src, Count) \
      __builtin_memcpy (Dst, Src, YY_CAST (YYSIZE_T, (Count)) * sizeof (*(Src)))
#  else
#   define YYCOPY(Dst, Src, Count)              \
      do                                        \
        {                                       \
          YYPTRDIFF_T yyi;                      \
          for (yyi = 0; yyi < (Count); yyi++)   \
            (Dst)[yyi] = (Src)[yyi];            \
        }                                       \
      while (0)
#  endif
# endif
#endif /* !YYCOPY_NEEDED */

/* YYFINAL -- State number of the termination state.  */
#define YYFINAL  60
/* YYLAST -- Last index in YYTABLE.  */
#define YYLAST   258

/* YYNTOKENS -- Number of terminals.  */
#define YYNTOKENS  39
/* YYNNTS -- Number of nonterminals.  */
#define YYNNTS  36
/* YYNRULES -- Number of rules.  */
#define YYNRULES  98
/* YYNSTATES -- Number of states.  */
#define YYNSTATES  186

/* YYMAXUTOK -- Last valid token kind.  */
#define YYMAXUTOK   284


/* YYTRANSLATE(TOKEN-NUM) -- Symbol number corresponding to TOKEN-NUM
   as returned by yylex, with out-of-bounds checking.  */
#define YYTRANSLATE(YYX)                                \
  (0 <= (YYX) && (YYX) <= YYMAXUTOK                     \
   ? YY_CAST (yysymbol_kind_t, yytranslate[YYX])        \
   : YYSYMBOL_YYUNDEF)

/* YYTRANSLATE[TOKEN-NUM] -- Symbol number corresponding to TOKEN-NUM
   as returned by yylex.  */
static const yytype_int8 yytranslate[] =
{
       0,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
      30,    31,     2,     2,    32,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,    38,
       2,    37,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,    33,     2,    34,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,    35,     2,    36,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     1,     2,     3,     4,
       5,     6,     7,     8,     9,    10,    11,    12,    13,    14,
      15,    16,    17,    18,    19,    20,    21,    22,    23,    24,
      25,    26,    27,    28,    29
};

#if YYDEBUG
/* YYRLINE[YYN] -- Source line where rule number YYN was defined.  */
static const yytype_int16 yyrline[] =
{
       0,    74,    74,    78,    82,    85,    88,    94,   101,   104,
     107,   111,   115,   119,   126,   129,   135,   141,   144,   152,
     159,   166,   175,   179,   186,   191,   200,   204,   212,   224,
     231,   238,   242,   246,   250,   254,   258,   262,   266,   272,
     279,   284,   288,   293,   297,   301,   307,   311,   316,   321,
     325,   330,   334,   340,   345,   355,   361,   366,   370,   375,
     380,   386,   399,   405,   412,   419,   431,   438,   447,   454,
     465,   472,   480,   487,   497,   505,   510,   516,   522,   528,
     532,   536,   540,   544,   566,   569,   573,   577,   581,   586,
     593,   597,   603,   610,   617,   624,   632,   642,   645
};
#endif

/** Accessing symbol of state STATE.  */
#define YY_ACCESSING_SYMBOL(State) YY_CAST (yysymbol_kind_t, yystos[State])

#if YYDEBUG || 0
/* The user-facing name of the symbol whose (internal) number is
   YYSYMBOL.  No bounds checking.  */
static const char *yysymbol_name (yysymbol_kind_t yysymbol) YY_ATTRIBUTE_UNUSED;

/* YYTNAME[SYMBOL-NUM] -- String name of the symbol SYMBOL-NUM.
   First, the terminals, then, starting at YYNTOKENS, nonterminals.  */
static const char *const yytname[] =
{
  "\"end of file\"", "error", "\"invalid token\"", "T_DIGIT", "T_ID",
  "T_FUNC", "T_RETURN", "T_MAIN", "T_IF", "T_ELSE", "T_WHILE", "T_CONST",
  "T_VOID", "T_CONTINUE", "T_BREAK", "T_INT", "T_ADD", "T_SUB", "T_TIMES",
  "T_DIV", "T_MOD", "T_EQUAL", "T_NOT_EQUAL", "T_LESS_THAN",
  "T_GREATER_THEN", "T_LESS_EQUAL", "T_GREATER_EQUAL", "T_LOGICAL_AND",
  "T_LOGICAL_OR", "T_NOT", "'('", "')'", "','", "'['", "']'", "'{'", "'}'",
  "'='", "';'", "$accept", "CompileUnit", "FuncDef", "FuncFormalParams",
  "FuncFormalParam", "FuncBasicParam", "FuncBasicParamArrays", "Block",
  "BlockItemList", "BlockItem", "Statement", "Cond", "Expr", "RelExp",
  "EqExp", "LAndExp", "LOrExp", "Decl", "ConstExp", "InitVal",
  "InitValList", "ConstDecl", "ConstDefs", "ConstInitVal", "ConstDef",
  "VarDef", "ArrayLists", "VarDecl", "VarDefs", "AddExp", "MulExp",
  "UnaryExp", "PrimaryExp", "LVal", "LValueList", "RealParamList", YY_NULLPTR
};

static const char *
yysymbol_name (yysymbol_kind_t yysymbol)
{
  return yytname[yysymbol];
}
#endif

#define YYPACT_NINF (-123)

#define yypact_value_is_default(Yyn) \
  ((Yyn) == YYPACT_NINF)

#define YYTABLE_NINF (-1)

#define yytable_value_is_error(Yyn) \
  0

/* YYPACT[STATE-NUM] -- Index in YYTABLE of the portion describing
   STATE-NUM.  */
static const yytype_int16 yypact[] =
{
     195,  -123,    33,    35,    18,   -14,    11,    37,    67,    23,
      43,    69,   218,   218,   218,   218,   105,    72,  -123,  -123,
    -123,    74,    80,   110,    71,    82,  -123,  -123,  -123,   122,
     106,  -123,  -123,    63,   163,   218,    84,    93,  -123,    98,
    -123,   218,   218,   144,   123,  -123,  -123,    21,  -123,    -6,
    -123,  -123,  -123,   124,   154,  -123,   146,  -123,  -123,  -123,
    -123,  -123,  -123,  -123,  -123,   218,   218,   218,   218,   218,
     218,   218,   218,   218,   218,   218,   218,   218,   218,  -123,
    -123,   111,   136,   218,    12,  -123,   142,    82,   156,    57,
      27,  -123,    14,    31,   192,    20,    59,   154,  -123,  -123,
      60,  -123,  -123,   122,   122,   122,   122,    80,    80,   110,
      71,   106,   106,  -123,  -123,  -123,   164,  -123,   218,  -123,
     170,   211,   181,   113,  -123,  -123,   223,   223,   218,    62,
     144,  -123,   181,   115,   181,   137,   183,   161,  -123,  -123,
     215,    20,  -123,  -123,  -123,  -123,   186,  -123,   181,   205,
     214,  -123,  -123,  -123,   122,    20,  -123,  -123,   181,  -123,
     181,  -123,  -123,  -123,    28,   194,  -123,    10,   199,  -123,
    -123,   223,  -123,  -123,  -123,    20,  -123,  -123,   204,  -123,
     238,  -123,  -123,  -123,   208,  -123
};

/* YYDEFACT[STATE-NUM] -- Default reduction number in state STATE-NUM.
   Performed when YYTABLE does not specify something else to do.  Zero
   means the default is an error.  */
static const yytype_int8 yydefact[] =
{
       0,    91,    93,     0,     0,     0,     0,     0,     0,     0,
       0,     0,     0,     0,     0,     0,     0,     0,     2,    38,
       3,    30,    46,    49,    51,    40,     6,    53,    54,    41,
      79,    83,    84,    92,     0,     0,    94,     0,    31,     0,
      92,     0,     0,     0,     0,    37,    36,    68,    75,     0,
      87,    88,    89,     0,     0,    22,     0,    24,    26,    27,
       1,     4,     5,     7,    29,     0,     0,     0,     0,     0,
       0,     0,     0,     0,     0,     0,     0,     0,     0,    85,
      97,     0,     0,     0,     0,    32,     0,    39,     0,     0,
       0,    62,     0,     0,     0,     0,    70,     0,    74,    90,
      68,    23,    25,    42,    43,    44,    45,    47,    48,    50,
      52,    77,    78,    80,    81,    82,     0,    86,     0,    95,
       0,     0,     0,     0,    14,    16,     0,     0,     0,    66,
       0,    61,     0,     0,     0,     0,     0,     0,    56,    69,
       0,     0,    76,    28,    98,    96,    17,     8,     0,     0,
      34,    35,    64,    65,    55,     0,    63,    10,     0,    12,
       0,    72,    58,    59,     0,     0,    71,     0,    18,     9,
      15,     0,    67,    11,    13,     0,    57,    73,     0,    19,
       0,    33,    60,    20,     0,    21
};

/* YYPGOTO[NTERM-NUM].  */
static const yytype_int16 yypgoto[] =
{
    -123,  -123,   226,    91,    95,  -123,  -123,  -120,  -123,   189,
       3,   207,    -4,   116,   175,   178,   147,    25,  -123,  -122,
    -123,  -123,  -123,  -123,   121,   157,   166,  -123,  -123,   -58,
     140,    -8,  -123,     1,  -123,  -123
};

/* YYDEFGOTO[NTERM-NUM].  */
static const yytype_uint8 yydefgoto[] =
{
       0,    17,    18,   123,   124,   125,   168,    19,    56,    57,
      58,    86,    21,    22,    23,    24,    25,    59,   152,   139,
     164,    27,    90,   153,    91,    48,    96,    28,    49,    29,
      30,    31,    32,    40,    36,    81
};

/* YYTABLE[YYPACT[STATE-NUM]] -- What to do in state STATE-NUM.  If
   positive, shift that token.  If negative, reduce the rule whose
   number is the opposite.  If YYTABLE_NINF, syntax error.  */
static const yytype_uint8 yytable[] =
{
      39,    33,   147,    20,    50,    51,    52,   103,   104,   105,
     106,    53,   157,   178,   159,   163,    41,    33,    33,   166,
      62,     1,     2,     1,     2,    26,    97,   121,   169,   121,
      80,    82,    98,   172,    12,    13,    12,    13,   173,    37,
     174,    42,    63,   122,   179,   132,   121,    14,    15,    14,
      15,    93,    43,   182,    94,   137,    38,    33,    95,   130,
     175,    45,   134,    34,   176,   131,    35,   113,   114,   115,
     154,    44,    60,    47,   116,     1,     2,     3,     4,   120,
       5,    46,     6,     7,     8,     9,    10,    11,    12,    13,
      94,   138,   140,    94,   128,   140,   141,    95,    71,   155,
      78,    14,    15,    65,    66,    67,    68,    16,     1,     2,
      72,     4,    64,     5,   144,     6,     7,    83,     9,    10,
      54,    12,    13,    84,    75,    76,    77,    33,    33,   150,
     151,    69,    70,   138,    14,    15,    85,   138,    73,    74,
      16,    55,   117,   118,   148,   149,   158,   149,    89,     1,
       2,   138,     4,    92,     5,    99,     6,     7,   100,     9,
      10,    54,    12,    13,     1,     2,     1,     2,   160,   149,
     119,   138,    33,   126,   181,    14,    15,    12,    13,    12,
      13,    16,   101,   133,   135,   107,   108,   127,    87,    87,
      14,    15,    14,    15,    79,   136,   137,   162,     1,     2,
       3,     4,   143,     5,   145,     6,     7,     8,     9,    10,
      11,    12,    13,   111,   112,   146,    16,   161,   165,   167,
     121,     1,     2,   171,    14,    15,     1,     2,   177,     4,
      16,     5,   180,     6,    12,    13,     9,    10,   183,    12,
      13,   184,   185,    61,   170,   102,   109,    14,    15,    88,
     110,   156,    14,    15,   142,   129,     0,     0,    16
};

static const yytype_int16 yycheck[] =
{
       4,     0,   122,     0,    12,    13,    14,    65,    66,    67,
      68,    15,   132,     3,   134,   137,    30,    16,    17,   141,
      17,     3,     4,     3,     4,     0,    32,    15,   148,    15,
      34,    35,    38,   155,    16,    17,    16,    17,   158,     4,
     160,    30,    17,    31,    34,    31,    15,    29,    30,    29,
      30,    30,    15,   175,    33,    35,    38,    56,    37,    32,
      32,    38,    31,    30,    36,    38,    33,    75,    76,    77,
     128,     4,     0,     4,    78,     3,     4,     5,     6,    83,
       8,    38,    10,    11,    12,    13,    14,    15,    16,    17,
      33,    95,    33,    33,    37,    33,    37,    37,    27,    37,
      37,    29,    30,    23,    24,    25,    26,    35,     3,     4,
      28,     6,    38,     8,   118,    10,    11,    33,    13,    14,
      15,    16,    17,    30,    18,    19,    20,   126,   127,   126,
     127,    21,    22,   137,    29,    30,    38,   141,    16,    17,
      35,    36,    31,    32,    31,    32,    31,    32,     4,     3,
       4,   155,     6,    30,     8,    31,    10,    11,     4,    13,
      14,    15,    16,    17,     3,     4,     3,     4,    31,    32,
      34,   175,   171,    31,   171,    29,    30,    16,    17,    16,
      17,    35,    36,    92,    93,    69,    70,    31,    41,    42,
      29,    30,    29,    30,    31,     3,    35,    36,     3,     4,
       5,     6,    38,     8,    34,    10,    11,    12,    13,    14,
      15,    16,    17,    73,    74,     4,    35,    34,     3,    33,
      15,     3,     4,     9,    29,    30,     3,     4,    34,     6,
      35,     8,    33,    10,    16,    17,    13,    14,    34,    16,
      17,     3,    34,    17,   149,    56,    71,    29,    30,    42,
      72,   130,    29,    30,    97,    89,    -1,    -1,    35
};

/* YYSTOS[STATE-NUM] -- The symbol kind of the accessing symbol of
   state STATE-NUM.  */
static const yytype_int8 yystos[] =
{
       0,     3,     4,     5,     6,     8,    10,    11,    12,    13,
      14,    15,    16,    17,    29,    30,    35,    40,    41,    46,
      49,    51,    52,    53,    54,    55,    56,    60,    66,    68,
      69,    70,    71,    72,    30,    33,    73,     4,    38,    51,
      72,    30,    30,    15,     4,    38,    38,     4,    64,    67,
      70,    70,    70,    51,    15,    36,    47,    48,    49,    56,
       0,    41,    49,    56,    38,    23,    24,    25,    26,    21,
      22,    27,    28,    16,    17,    18,    19,    20,    37,    31,
      51,    74,    51,    33,    30,    38,    50,    55,    50,     4,
      61,    63,    30,    30,    33,    37,    65,    32,    38,    31,
       4,    36,    48,    68,    68,    68,    68,    52,    52,    53,
      54,    69,    69,    70,    70,    70,    51,    31,    32,    34,
      51,    15,    31,    42,    43,    44,    31,    31,    37,    65,
      32,    38,    31,    42,    31,    42,     3,    35,    51,    58,
      33,    37,    64,    38,    51,    34,     4,    46,    31,    32,
      49,    49,    57,    62,    68,    37,    63,    46,    31,    46,
      31,    34,    36,    58,    59,     3,    58,    33,    45,    46,
      43,     9,    58,    46,    46,    32,    36,    34,     3,    34,
      33,    49,    58,    34,     3,    34
};

/* YYR1[RULE-NUM] -- Symbol kind of the left-hand side of rule RULE-NUM.  */
static const yytype_int8 yyr1[] =
{
       0,    39,    40,    40,    40,    40,    40,    40,    41,    41,
      41,    41,    41,    41,    42,    42,    43,    44,    44,    45,
      45,    45,    46,    46,    47,    47,    48,    48,    49,    49,
      49,    49,    49,    49,    49,    49,    49,    49,    49,    50,
      51,    52,    52,    52,    52,    52,    53,    53,    53,    54,
      54,    55,    55,    56,    56,    57,    58,    58,    58,    59,
      59,    60,    61,    61,    62,    63,    63,    63,    64,    64,
      64,    64,    65,    65,    66,    67,    67,    68,    68,    68,
      69,    69,    69,    69,    70,    70,    70,    70,    70,    70,
      71,    71,    71,    72,    72,    73,    73,    74,    74
};

/* YYR2[RULE-NUM] -- Number of symbols on the right-hand side of rule RULE-NUM.  */
static const yytype_int8 yyr2[] =
{
       0,     2,     1,     1,     2,     2,     1,     2,     5,     6,
       5,     6,     5,     6,     1,     3,     1,     2,     3,     2,
       3,     4,     2,     3,     1,     2,     1,     1,     4,     2,
       1,     2,     3,     7,     5,     5,     2,     2,     1,     1,
       1,     1,     3,     3,     3,     3,     1,     3,     3,     1,
       3,     1,     3,     1,     1,     1,     1,     3,     2,     1,
       3,     4,     1,     3,     1,     3,     2,     4,     1,     3,
       2,     4,     3,     4,     3,     1,     3,     3,     3,     1,
       3,     3,     3,     1,     1,     3,     4,     2,     2,     2,
       3,     1,     1,     1,     2,     3,     4,     1,     3
};


enum { YYENOMEM = -2 };

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (yychar = YYEMPTY)

#define YYACCEPT        goto yyacceptlab
#define YYABORT         goto yyabortlab
#define YYERROR         goto yyerrorlab
#define YYNOMEM         goto yyexhaustedlab


#define YYRECOVERING()  (!!yyerrstatus)

#define YYBACKUP(Token, Value)                                    \
  do                                                              \
    if (yychar == YYEMPTY)                                        \
      {                                                           \
        yychar = (Token);                                         \
        yylval = (Value);                                         \
        YYPOPSTACK (yylen);                                       \
        yystate = *yyssp;                                         \
        goto yybackup;                                            \
      }                                                           \
    else                                                          \
      {                                                           \
        yyerror (YY_("syntax error: cannot back up")); \
        YYERROR;                                                  \
      }                                                           \
  while (0)

/* Backward compatibility with an undocumented macro.
   Use YYerror or YYUNDEF. */
#define YYERRCODE YYUNDEF


/* Enable debugging if requested.  */
#if YYDEBUG

# ifndef YYFPRINTF
#  include <stdio.h> /* INFRINGES ON USER NAME SPACE */
#  define YYFPRINTF fprintf
# endif

# define YYDPRINTF(Args)                        \
do {                                            \
  if (yydebug)                                  \
    YYFPRINTF Args;                             \
} while (0)




# define YY_SYMBOL_PRINT(Title, Kind, Value, Location)                    \
do {                                                                      \
  if (yydebug)                                                            \
    {                                                                     \
      YYFPRINTF (stderr, "%s ", Title);                                   \
      yy_symbol_print (stderr,                                            \
                  Kind, Value); \
      YYFPRINTF (stderr, "\n");                                           \
    }                                                                     \
} while (0)


/*-----------------------------------.
| Print this symbol's value on YYO.  |
`-----------------------------------*/

static void
yy_symbol_value_print (FILE *yyo,
                       yysymbol_kind_t yykind, YYSTYPE const * const yyvaluep)
{
  FILE *yyoutput = yyo;
  YY_USE (yyoutput);
  if (!yyvaluep)
    return;
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  YY_USE (yykind);
  YY_IGNORE_MAYBE_UNINITIALIZED_END
}


/*---------------------------.
| Print this symbol on YYO.  |
`---------------------------*/

static void
yy_symbol_print (FILE *yyo,
                 yysymbol_kind_t yykind, YYSTYPE const * const yyvaluep)
{
  YYFPRINTF (yyo, "%s %s (",
             yykind < YYNTOKENS ? "token" : "nterm", yysymbol_name (yykind));

  yy_symbol_value_print (yyo, yykind, yyvaluep);
  YYFPRINTF (yyo, ")");
}

/*------------------------------------------------------------------.
| yy_stack_print -- Print the state stack from its BOTTOM up to its |
| TOP (included).                                                   |
`------------------------------------------------------------------*/

static void
yy_stack_print (yy_state_t *yybottom, yy_state_t *yytop)
{
  YYFPRINTF (stderr, "Stack now");
  for (; yybottom <= yytop; yybottom++)
    {
      int yybot = *yybottom;
      YYFPRINTF (stderr, " %d", yybot);
    }
  YYFPRINTF (stderr, "\n");
}

# define YY_STACK_PRINT(Bottom, Top)                            \
do {                                                            \
  if (yydebug)                                                  \
    yy_stack_print ((Bottom), (Top));                           \
} while (0)


/*------------------------------------------------.
| Report that the YYRULE is going to be reduced.  |
`------------------------------------------------*/

static void
yy_reduce_print (yy_state_t *yyssp, YYSTYPE *yyvsp,
                 int yyrule)
{
  int yylno = yyrline[yyrule];
  int yynrhs = yyr2[yyrule];
  int yyi;
  YYFPRINTF (stderr, "Reducing stack by rule %d (line %d):\n",
             yyrule - 1, yylno);
  /* The symbols being reduced.  */
  for (yyi = 0; yyi < yynrhs; yyi++)
    {
      YYFPRINTF (stderr, "   $%d = ", yyi + 1);
      yy_symbol_print (stderr,
                       YY_ACCESSING_SYMBOL (+yyssp[yyi + 1 - yynrhs]),
                       &yyvsp[(yyi + 1) - (yynrhs)]);
      YYFPRINTF (stderr, "\n");
    }
}

# define YY_REDUCE_PRINT(Rule)          \
do {                                    \
  if (yydebug)                          \
    yy_reduce_print (yyssp, yyvsp, Rule); \
} while (0)

/* Nonzero means print parse trace.  It is left uninitialized so that
   multiple parsers can coexist.  */
int yydebug;
#else /* !YYDEBUG */
# define YYDPRINTF(Args) ((void) 0)
# define YY_SYMBOL_PRINT(Title, Kind, Value, Location)
# define YY_STACK_PRINT(Bottom, Top)
# define YY_REDUCE_PRINT(Rule)
#endif /* !YYDEBUG */


/* YYINITDEPTH -- initial size of the parser's stacks.  */
#ifndef YYINITDEPTH
# define YYINITDEPTH 200
#endif

/* YYMAXDEPTH -- maximum size the stacks can grow to (effective only
   if the built-in stack extension method is used).

   Do not make this value too large; the results are undefined if
   YYSTACK_ALLOC_MAXIMUM < YYSTACK_BYTES (YYMAXDEPTH)
   evaluated with infinite-precision integer arithmetic.  */

#ifndef YYMAXDEPTH
# define YYMAXDEPTH 10000
#endif






/*-----------------------------------------------.
| Release the memory associated to this symbol.  |
`-----------------------------------------------*/

static void
yydestruct (const char *yymsg,
            yysymbol_kind_t yykind, YYSTYPE *yyvaluep)
{
  YY_USE (yyvaluep);
  if (!yymsg)
    yymsg = "Deleting";
  YY_SYMBOL_PRINT (yymsg, yykind, yyvaluep, yylocationp);

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  YY_USE (yykind);
  YY_IGNORE_MAYBE_UNINITIALIZED_END
}


/* Lookahead token kind.  */
int yychar;

/* The semantic value of the lookahead symbol.  */
YYSTYPE yylval;
/* Number of syntax errors so far.  */
int yynerrs;




/*----------.
| yyparse.  |
`----------*/

int
yyparse (void)
{
    yy_state_fast_t yystate = 0;
    /* Number of tokens to shift before error messages enabled.  */
    int yyerrstatus = 0;

    /* Refer to the stacks through separate pointers, to allow yyoverflow
       to reallocate them elsewhere.  */

    /* Their size.  */
    YYPTRDIFF_T yystacksize = YYINITDEPTH;

    /* The state stack: array, bottom, top.  */
    yy_state_t yyssa[YYINITDEPTH];
    yy_state_t *yyss = yyssa;
    yy_state_t *yyssp = yyss;

    /* The semantic value stack: array, bottom, top.  */
    YYSTYPE yyvsa[YYINITDEPTH];
    YYSTYPE *yyvs = yyvsa;
    YYSTYPE *yyvsp = yyvs;

  int yyn;
  /* The return value of yyparse.  */
  int yyresult;
  /* Lookahead symbol kind.  */
  yysymbol_kind_t yytoken = YYSYMBOL_YYEMPTY;
  /* The variables used to return semantic value and location from the
     action routines.  */
  YYSTYPE yyval;



#define YYPOPSTACK(N)   (yyvsp -= (N), yyssp -= (N))

  /* The number of symbols on the RHS of the reduced rule.
     Keep to zero when no symbol should be popped.  */
  int yylen = 0;

  YYDPRINTF ((stderr, "Starting parse\n"));

  yychar = YYEMPTY; /* Cause a token to be read.  */

  goto yysetstate;


/*------------------------------------------------------------.
| yynewstate -- push a new state, which is found in yystate.  |
`------------------------------------------------------------*/
yynewstate:
  /* In all cases, when you get here, the value and location stacks
     have just been pushed.  So pushing a state here evens the stacks.  */
  yyssp++;


/*--------------------------------------------------------------------.
| yysetstate -- set current state (the top of the stack) to yystate.  |
`--------------------------------------------------------------------*/
yysetstate:
  YYDPRINTF ((stderr, "Entering state %d\n", yystate));
  YY_ASSERT (0 <= yystate && yystate < YYNSTATES);
  YY_IGNORE_USELESS_CAST_BEGIN
  *yyssp = YY_CAST (yy_state_t, yystate);
  YY_IGNORE_USELESS_CAST_END
  YY_STACK_PRINT (yyss, yyssp);

  if (yyss + yystacksize - 1 <= yyssp)
#if !defined yyoverflow && !defined YYSTACK_RELOCATE
    YYNOMEM;
#else
    {
      /* Get the current used size of the three stacks, in elements.  */
      YYPTRDIFF_T yysize = yyssp - yyss + 1;

# if defined yyoverflow
      {
        /* Give user a chance to reallocate the stack.  Use copies of
           these so that the &'s don't force the real ones into
           memory.  */
        yy_state_t *yyss1 = yyss;
        YYSTYPE *yyvs1 = yyvs;

        /* Each stack pointer address is followed by the size of the
           data in use in that stack, in bytes.  This used to be a
           conditional around just the two extra args, but that might
           be undefined if yyoverflow is a macro.  */
        yyoverflow (YY_("memory exhausted"),
                    &yyss1, yysize * YYSIZEOF (*yyssp),
                    &yyvs1, yysize * YYSIZEOF (*yyvsp),
                    &yystacksize);
        yyss = yyss1;
        yyvs = yyvs1;
      }
# else /* defined YYSTACK_RELOCATE */
      /* Extend the stack our own way.  */
      if (YYMAXDEPTH <= yystacksize)
        YYNOMEM;
      yystacksize *= 2;
      if (YYMAXDEPTH < yystacksize)
        yystacksize = YYMAXDEPTH;

      {
        yy_state_t *yyss1 = yyss;
        union yyalloc *yyptr =
          YY_CAST (union yyalloc *,
                   YYSTACK_ALLOC (YY_CAST (YYSIZE_T, YYSTACK_BYTES (yystacksize))));
        if (! yyptr)
          YYNOMEM;
        YYSTACK_RELOCATE (yyss_alloc, yyss);
        YYSTACK_RELOCATE (yyvs_alloc, yyvs);
#  undef YYSTACK_RELOCATE
        if (yyss1 != yyssa)
          YYSTACK_FREE (yyss1);
      }
# endif

      yyssp = yyss + yysize - 1;
      yyvsp = yyvs + yysize - 1;

      YY_IGNORE_USELESS_CAST_BEGIN
      YYDPRINTF ((stderr, "Stack size increased to %ld\n",
                  YY_CAST (long, yystacksize)));
      YY_IGNORE_USELESS_CAST_END

      if (yyss + yystacksize - 1 <= yyssp)
        YYABORT;
    }
#endif /* !defined yyoverflow && !defined YYSTACK_RELOCATE */


  if (yystate == YYFINAL)
    YYACCEPT;

  goto yybackup;


/*-----------.
| yybackup.  |
`-----------*/
yybackup:
  /* Do appropriate processing given the current state.  Read a
     lookahead token if we need one and don't already have one.  */

  /* First try to decide what to do without reference to lookahead token.  */
  yyn = yypact[yystate];
  if (yypact_value_is_default (yyn))
    goto yydefault;

  /* Not known => get a lookahead token if don't already have one.  */

  /* YYCHAR is either empty, or end-of-input, or a valid lookahead.  */
  if (yychar == YYEMPTY)
    {
      YYDPRINTF ((stderr, "Reading a token\n"));
      yychar = yylex ();
    }

  if (yychar <= YYEOF)
    {
      yychar = YYEOF;
      yytoken = YYSYMBOL_YYEOF;
      YYDPRINTF ((stderr, "Now at end of input.\n"));
    }
  else if (yychar == YYerror)
    {
      /* The scanner already issued an error message, process directly
         to error recovery.  But do not keep the error token as
         lookahead, it is too special and may lead us to an endless
         loop in error recovery. */
      yychar = YYUNDEF;
      yytoken = YYSYMBOL_YYerror;
      goto yyerrlab1;
    }
  else
    {
      yytoken = YYTRANSLATE (yychar);
      YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc);
    }

  /* If the proper action on seeing token YYTOKEN is to reduce or to
     detect an error, take that action.  */
  yyn += yytoken;
  if (yyn < 0 || YYLAST < yyn || yycheck[yyn] != yytoken)
    goto yydefault;
  yyn = yytable[yyn];
  if (yyn <= 0)
    {
      if (yytable_value_is_error (yyn))
        goto yyerrlab;
      yyn = -yyn;
      goto yyreduce;
    }

  /* Count tokens shifted since error; after three, turn off error
     status.  */
  if (yyerrstatus)
    yyerrstatus--;

  /* Shift the lookahead token.  */
  YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc);
  yystate = yyn;
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END

  /* Discard the shifted token.  */
  yychar = YYEMPTY;
  goto yynewstate;


/*-----------------------------------------------------------.
| yydefault -- do the default action for the current state.  |
`-----------------------------------------------------------*/
yydefault:
  yyn = yydefact[yystate];
  if (yyn == 0)
    goto yyerrlab;
  goto yyreduce;


/*-----------------------------.
| yyreduce -- do a reduction.  |
`-----------------------------*/
yyreduce:
  /* yyn is the number of a rule to reduce with.  */
  yylen = yyr2[yyn];

  /* If YYLEN is nonzero, implement the default value of the action:
     '$$ = $1'.

     Otherwise, the following line sets YYVAL to garbage.
     This behavior is undocumented and Bison
     users should not rely upon it.  Assigning to YYVAL
     unconditionally makes the parser a bit smaller, and it avoids a
     GCC warning that YYVAL may be used uninitialized.  */
  yyval = yyvsp[1-yylen];


  YY_REDUCE_PRINT (yyn);
  switch (yyn)
    {
  case 2: /* CompileUnit: FuncDef  */
#line 74 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                      {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_COMPILE_UNIT, (yyvsp[0].node));
        ast_root = (yyval.node);
    }
#line 1290 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 3: /* CompileUnit: Statement  */
#line 78 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_COMPILE_UNIT, (yyvsp[0].node));
        ast_root = (yyval.node);
    }
#line 1299 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 4: /* CompileUnit: CompileUnit FuncDef  */
#line 82 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                          {
        (yyval.node) = insert_ast_node((yyvsp[-1].node), (yyvsp[0].node));
    }
#line 1307 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 5: /* CompileUnit: CompileUnit Statement  */
#line 85 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                            {
        (yyval.node) = insert_ast_node((yyvsp[-1].node), (yyvsp[0].node));
    }
#line 1315 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 6: /* CompileUnit: Decl  */
#line 89 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_COMPILE_UNIT, (yyvsp[0].node));
		// $$ = create_contain_node(ast_operator_type::AST_OP_DECL, $1);
        ast_root = (yyval.node);
	}
#line 1325 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 7: /* CompileUnit: CompileUnit Decl  */
#line 95 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = insert_ast_node((yyvsp[-1].node), (yyvsp[0].node));
	}
#line 1333 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 8: /* FuncDef: T_FUNC T_ID '(' ')' Block  */
#line 101 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                                     {
        (yyval.node) = create_func_def((yyvsp[-3].var_id).lineno, (yyvsp[-3].var_id).id, (yyvsp[0].node), nullptr);
    }
#line 1341 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 9: /* FuncDef: T_FUNC T_ID '(' FuncFormalParams ')' Block  */
#line 104 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                                                 {
        (yyval.node) = create_func_def((yyvsp[-4].var_id).lineno, (yyvsp[-4].var_id).id, (yyvsp[0].node), (yyvsp[-2].node));
    }
#line 1349 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 10: /* FuncDef: T_VOID T_ID '(' ')' Block  */
#line 108 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
        (yyval.node) = create_func_def(BasicType::TYPE_VOID,(yyvsp[-3].var_id).lineno, (yyvsp[-3].var_id).id, (yyvsp[0].node), nullptr);
	}
#line 1357 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 11: /* FuncDef: T_VOID T_ID '(' FuncFormalParams ')' Block  */
#line 112 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
        (yyval.node) = create_func_def(BasicType::TYPE_VOID,(yyvsp[-4].var_id).lineno, (yyvsp[-4].var_id).id, (yyvsp[0].node), (yyvsp[-2].node));
	}
#line 1365 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 12: /* FuncDef: T_INT T_ID '(' ')' Block  */
#line 116 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
        (yyval.node) = create_func_def(BasicType::TYPE_INT,(yyvsp[-3].var_id).lineno, (yyvsp[-3].var_id).id, (yyvsp[0].node), nullptr);
	}
#line 1373 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 13: /* FuncDef: T_INT T_ID '(' FuncFormalParams ')' Block  */
#line 120 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
        (yyval.node) = create_func_def(BasicType::TYPE_INT,(yyvsp[-4].var_id).lineno, (yyvsp[-4].var_id).id, (yyvsp[0].node), (yyvsp[-2].node));
	}
#line 1381 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 14: /* FuncFormalParams: FuncFormalParam  */
#line 126 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                                    {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_FUNC_FORMAL_PARAMS, (yyvsp[0].node));
    }
#line 1389 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 15: /* FuncFormalParams: FuncFormalParams ',' FuncFormalParam  */
#line 129 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                                           {
        (yyval.node) = insert_ast_node((yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1397 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 16: /* FuncFormalParam: FuncBasicParam  */
#line 135 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                                  {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1405 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 17: /* FuncBasicParam: T_INT T_ID  */
#line 141 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                            {
        (yyval.node) = create_func_formal_param((yyvsp[0].var_id).lineno, (yyvsp[0].var_id).id);
    }
#line 1413 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 18: /* FuncBasicParam: T_INT T_ID FuncBasicParamArrays  */
#line 145 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		ast_node * id_node = new_ast_leaf_node(var_id_attr{(yyvsp[-1].var_id).id, (yyvsp[-1].var_id).lineno});
		ast_node * return_node = create_contain_node(ast_operator_type::AST_OP_FUNC_ARRAY, id_node);
		update_array_ast_node_info((yyvsp[0].node));
		(yyval.node) = insert_ast_node(return_node, (yyvsp[0].node));
	}
#line 1424 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 19: /* FuncBasicParamArrays: '[' ']'  */
#line 153 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {	
		ast_node *num_node = new_ast_leaf_node(digit_int_attr{0,0});
		ast_node *array_node = new_ast_node(ast_operator_type::AST_OP_ARRAY, nullptr);
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_ARRAY,num_node,array_node,nullptr);

	}
#line 1435 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 20: /* FuncBasicParamArrays: '[' T_DIGIT ']'  */
#line 160 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		ast_node *num_node = new_ast_leaf_node(digit_int_attr{(yyvsp[-1].integer_num).val,(yyvsp[-1].integer_num).lineno});
		ast_node *array_node = new_ast_node(ast_operator_type::AST_OP_ARRAY, nullptr);
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_ARRAY,num_node,array_node,nullptr);

	}
#line 1446 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 21: /* FuncBasicParamArrays: FuncBasicParamArrays '[' T_DIGIT ']'  */
#line 167 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		ast_node * num_node = new_ast_leaf_node(digit_int_attr{(yyvsp[-1].integer_num).val, (yyvsp[-1].integer_num).lineno});
		ast_node * array_node = new_ast_node(ast_operator_type::AST_OP_ARRAY,nullptr);
        (yyval.node) = array_insert_ast_node((yyvsp[-3].node),num_node,array_node);
	}
#line 1456 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 22: /* Block: '{' '}'  */
#line 175 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                {
        // 语句块没有语句
        (yyval.node) = nullptr;
    }
#line 1465 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 23: /* Block: '{' BlockItemList '}'  */
#line 179 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                            {
        // 语句块含有语句
        (yyval.node) = (yyvsp[-1].node);
    }
#line 1474 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 24: /* BlockItemList: BlockItem  */
#line 186 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                          {
        // 第一个左侧的孩子节点归约成Block父节点，后续语句可不断作为孩子追加到block中
        // 创建一个AST_OP_BLOCK类型的中间节点，孩子为Statement($1)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_BLOCK, (yyvsp[0].node), nullptr);
    }
#line 1484 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 25: /* BlockItemList: BlockItemList BlockItem  */
#line 191 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                               {
        // 采用左递归的文法产生式，可以使得Block节点在上个产生式创建，后续递归追加孩子节点
        // 请注意，不要采用右递归，左递归翻遍孩子的追加
        // BlockItem($2)作为Block($1)的孩子 
        (yyval.node) = insert_ast_node((yyvsp[-1].node), (yyvsp[0].node));
    }
#line 1495 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 26: /* BlockItem: Statement  */
#line 200 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                       {
	
        (yyval.node) = (yyvsp[0].node);
    }
#line 1504 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 27: /* BlockItem: Decl  */
#line 205 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1512 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 28: /* Statement: LVal '=' Expr ';'  */
#line 212 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                              {
        // 归约到Statement时要执行的语义动作程序
        // 赋值语句，不显示值

		// 变量节点
		//ast_node * id_node = new_ast_leaf_node(var_id_attr{$1.id, $1.lineno});

		//free($1.id);

        // 创建一个AST_OP_ASSIGN类型的中间节点，孩子为Id和Expr($3)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_ASSIGN, (yyvsp[-3].node), (yyvsp[-1].node), nullptr);
    }
#line 1529 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 29: /* Statement: Expr ';'  */
#line 224 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
               {
        // Expr归约到Statement时要执行的语义动作程序
        // 表达式语句，不显示表达式的值

        // 创建一个AST_OP_EXPR类型的中间节点，孩子为Expr($1)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_EXPR, (yyvsp[-1].node), nullptr);
    }
#line 1541 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 30: /* Statement: Expr  */
#line 231 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
           {
        // Expr归约到Statement时要执行的语义动作程序
        // 表达式语句，需要显示表达式的值

        // 创建一个AST_OP_EXPR_SHOW类型的中间节点，孩子为Expr($1)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_EXPR_SHOW, (yyvsp[0].node), nullptr);
    }
#line 1553 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 31: /* Statement: T_RETURN ';'  */
#line 239 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_RETURN_STATEMENT, nullptr);
	}
#line 1561 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 32: /* Statement: T_RETURN Expr ';'  */
#line 242 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                        {
        // 返回语句
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_RETURN_STATEMENT, (yyvsp[-1].node), nullptr);
    }
#line 1570 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 33: /* Statement: T_IF '(' Cond ')' Statement T_ELSE Statement  */
#line 247 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_IF,(yyvsp[-4].node),(yyvsp[-2].node),(yyvsp[0].node),nullptr);
	}
#line 1578 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 34: /* Statement: T_IF '(' Cond ')' Statement  */
#line 251 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_IF,(yyvsp[-2].node),(yyvsp[0].node),nullptr);
	}
#line 1586 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 35: /* Statement: T_WHILE '(' Cond ')' Statement  */
#line 255 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_WHILE,(yyvsp[-2].node),(yyvsp[0].node),nullptr);
	}
#line 1594 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 36: /* Statement: T_BREAK ';'  */
#line 259 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_leaf_node(BasicType::TYPE_BREAK,0);
	}
#line 1602 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 37: /* Statement: T_CONTINUE ';'  */
#line 263 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_leaf_node(BasicType::TYPE_CONTINUE,0);
	}
#line 1610 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 38: /* Statement: Block  */
#line 267 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1618 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 39: /* Cond: LOrExp  */
#line 273 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		// 
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_COND, (yyvsp[0].node),nullptr);
	}
#line 1627 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 40: /* Expr: LOrExp  */
#line 279 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
              { 
        (yyval.node) = (yyvsp[0].node); 
    }
#line 1635 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 41: /* RelExp: AddExp  */
#line 285 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1643 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 42: /* RelExp: RelExp T_LESS_THAN AddExp  */
#line 289 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		//
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_LESS_THAN, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 1652 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 43: /* RelExp: RelExp T_GREATER_THEN AddExp  */
#line 294 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_GREATER_THAN, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 1660 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 44: /* RelExp: RelExp T_LESS_EQUAL AddExp  */
#line 298 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_LESS_EQUAL, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 1668 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 45: /* RelExp: RelExp T_GREATER_EQUAL AddExp  */
#line 302 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_GREATER_EQUAL, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 1676 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 46: /* EqExp: RelExp  */
#line 308 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1684 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 47: /* EqExp: EqExp T_EQUAL RelExp  */
#line 312 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_EQUAL, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
		
	}
#line 1693 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 48: /* EqExp: EqExp T_NOT_EQUAL RelExp  */
#line 317 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_NOT_EQUAL, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 1701 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 49: /* LAndExp: EqExp  */
#line 322 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1709 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 50: /* LAndExp: LAndExp T_LOGICAL_AND EqExp  */
#line 326 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_LOGICAL_AND, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 1717 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 51: /* LOrExp: LAndExp  */
#line 331 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1725 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 52: /* LOrExp: LOrExp T_LOGICAL_OR LAndExp  */
#line 335 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_LOGICAL_OR, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 1733 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 53: /* Decl: ConstDecl  */
#line 341 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		// $$ = new_ast_node(ast_operator_type::AST_OP_DECL, $1, nullptr);
		(yyval.node) = (yyvsp[0].node);
	}
#line 1742 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 54: /* Decl: VarDecl  */
#line 346 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		// $$ = new_ast_node(ast_operator_type::AST_OP_DECL, $1, nullptr);
		(yyval.node) = (yyvsp[0].node);
	}
#line 1751 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 55: /* ConstExp: AddExp  */
#line 356 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1759 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 56: /* InitVal: Expr  */
#line 362 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = (yyvsp[0].node);
		
	}
#line 1768 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 57: /* InitVal: '{' InitValList '}'  */
#line 367 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = (yyvsp[-1].node);
	}
#line 1776 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 58: /* InitVal: '{' '}'  */
#line 371 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_ARRAY_EMPTY, nullptr);
	}
#line 1784 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 59: /* InitValList: InitVal  */
#line 376 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		// $$ = $1;
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_INIT_VAL_LIST, (yyvsp[0].node));
	}
#line 1793 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 60: /* InitValList: InitValList ',' InitVal  */
#line 381 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
        (yyval.node) = insert_ast_node((yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1801 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 61: /* ConstDecl: T_CONST T_INT ConstDefs ';'  */
#line 387 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		//TYPE_INT = 2
		ast_node * id_node = new_ast_leaf_node(BasicType::TYPE_INT,0);

        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_CONST_DECL, id_node, (yyvsp[-1].node), nullptr);

	}
#line 1813 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 62: /* ConstDefs: ConstDef  */
#line 400 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		//$$ = $1;
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_CONST_DEF, (yyvsp[0].node));

	}
#line 1823 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 63: /* ConstDefs: ConstDefs ',' ConstDef  */
#line 406 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
        (yyval.node) = insert_ast_node((yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1831 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 64: /* ConstInitVal: ConstExp  */
#line 413 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1839 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 65: /* ConstDef: T_ID '=' ConstInitVal  */
#line 420 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
        // 赋值语句，不显示值
		// 变量节点
		ast_node * id_node = new_ast_leaf_node(var_id_attr{(yyvsp[-2].var_id).id, (yyvsp[-2].var_id).lineno});

		free((yyvsp[-2].var_id).id);

        // 创建一个AST_OP_ConstDef类型的中间节点，孩子为Id和ConstInitVal($3)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_ASSIGN, id_node, (yyvsp[0].node), nullptr);

	}
#line 1855 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 66: /* ConstDef: T_ID ArrayLists  */
#line 432 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		// ?
		ast_node * id_node = new_ast_leaf_node(var_id_attr{(yyvsp[-1].var_id).id, (yyvsp[-1].var_id).lineno});
		update_array_ast_node_info((yyvsp[0].node));
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_ARRAY_DEF, id_node,(yyvsp[0].node), nullptr);
	}
#line 1866 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 67: /* ConstDef: T_ID ArrayLists '=' InitVal  */
#line 439 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		ast_node * id_node = new_ast_leaf_node(var_id_attr{(yyvsp[-3].var_id).id, (yyvsp[-3].var_id).lineno});
		update_array_ast_node_info((yyvsp[-2].node));
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_ARRAY_DEF, id_node,(yyvsp[-2].node),(yyvsp[0].node), nullptr);
	}
#line 1876 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 68: /* VarDef: T_ID  */
#line 448 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		ast_node * id_node = new_ast_leaf_node(var_id_attr{(yyvsp[0].var_id).id, (yyvsp[0].var_id).lineno});
		
		// $$ = new_ast_node(ast_operator_type::AST_OP_VAR_DEF, $1, nullptr);
		(yyval.node) = id_node;
	}
#line 1887 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 69: /* VarDef: T_ID '=' InitVal  */
#line 455 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		// 赋值语句，不显示值
		// 变量节点
		ast_node * id_node = new_ast_leaf_node(var_id_attr{(yyvsp[-2].var_id).id, (yyvsp[-2].var_id).lineno});

		free((yyvsp[-2].var_id).id);

        // 创建一个AST_OP_ConstDef类型的中间节点，孩子为Id和ConstInitVal($3)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_ASSIGN, id_node, (yyvsp[0].node), nullptr);
	}
#line 1902 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 70: /* VarDef: T_ID ArrayLists  */
#line 466 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		// ?
		ast_node * id_node = new_ast_leaf_node(var_id_attr{(yyvsp[-1].var_id).id, (yyvsp[-1].var_id).lineno});
		update_array_ast_node_info((yyvsp[0].node));
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_ARRAY_DEF, id_node,(yyvsp[0].node), nullptr);
	}
#line 1913 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 71: /* VarDef: T_ID ArrayLists '=' InitVal  */
#line 473 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		ast_node * id_node = new_ast_leaf_node(var_id_attr{(yyvsp[-3].var_id).id, (yyvsp[-3].var_id).lineno});
		update_array_ast_node_info((yyvsp[-2].node));
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_ARRAY_DEF, id_node,(yyvsp[-2].node),(yyvsp[0].node), nullptr);
	}
#line 1923 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 72: /* ArrayLists: '[' T_DIGIT ']'  */
#line 481 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		
        ast_node * num_node = new_ast_leaf_node(digit_int_attr{(yyvsp[-1].integer_num).val, (yyvsp[-1].integer_num).lineno});
		ast_node * array_node = new_ast_node(ast_operator_type::AST_OP_ARRAY,nullptr);
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_ARRAY,num_node,array_node,nullptr);
	}
#line 1934 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 73: /* ArrayLists: ArrayLists '[' T_DIGIT ']'  */
#line 488 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
        ast_node * num_node = new_ast_leaf_node(digit_int_attr{(yyvsp[-1].integer_num).val, (yyvsp[-1].integer_num).lineno});
		ast_node * array_node = new_ast_node(ast_operator_type::AST_OP_ARRAY,nullptr);

        (yyval.node) = array_insert_ast_node((yyvsp[-3].node),num_node,array_node);

	}
#line 1946 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 74: /* VarDecl: T_INT VarDefs ';'  */
#line 498 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		//TYPE_INT = 2
		ast_node * id_node = new_ast_leaf_node(BasicType::TYPE_INT,0);

        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_VAR_DECL, id_node, (yyvsp[-1].node), nullptr);
	}
#line 1957 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 75: /* VarDefs: VarDef  */
#line 506 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		// $$ = $1;
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_VAR_DEF, (yyvsp[0].node));
	}
#line 1966 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 76: /* VarDefs: VarDefs ',' VarDef  */
#line 511 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {	
        (yyval.node) = insert_ast_node((yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1974 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 77: /* AddExp: AddExp T_ADD MulExp  */
#line 516 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                             {
        /* Expr = Expr + Term */

        // 创建一个AST_OP_ADD类型的中间节点，孩子为Expr($1)和Term($3)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_ADD, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
    }
#line 1985 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 78: /* AddExp: AddExp T_SUB MulExp  */
#line 522 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                          {
        /* Expr = Expr + Term */

        // 创建一个AST_OP_ADD类型的中间节点，孩子为Expr($1)和Term($3)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_SUB, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
    }
#line 1996 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 79: /* AddExp: MulExp  */
#line 528 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
               {
		(yyval.node) = (yyvsp[0].node);
	}
#line 2004 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 80: /* MulExp: MulExp T_TIMES UnaryExp  */
#line 533 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_TIMES,(yyvsp[-2].node),(yyvsp[0].node),nullptr);
	}
#line 2012 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 81: /* MulExp: MulExp T_DIV UnaryExp  */
#line 537 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_DIV,(yyvsp[-2].node),(yyvsp[0].node),nullptr);
	}
#line 2020 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 82: /* MulExp: MulExp T_MOD UnaryExp  */
#line 541 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_MOD,(yyvsp[-2].node),(yyvsp[0].node),nullptr);
	}
#line 2028 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 83: /* MulExp: UnaryExp  */
#line 545 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		/* Expr = Term */
        (yyval.node) = (yyvsp[0].node);
	}
#line 2037 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 84: /* UnaryExp: PrimaryExp  */
#line 566 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                      {
        (yyval.node) = (yyvsp[0].node);
    }
#line 2045 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 85: /* UnaryExp: T_ID '(' ')'  */
#line 569 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                   {
        // 用户自定义的不含实参的函数调用
        (yyval.node) = create_func_call((yyvsp[-2].var_id).lineno, (yyvsp[-2].var_id).id, nullptr);
    }
#line 2054 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 86: /* UnaryExp: T_ID '(' RealParamList ')'  */
#line 573 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                                 {
        // 用户自定义的含有实参的参数调用
        (yyval.node) = create_func_call((yyvsp[-3].var_id).lineno, (yyvsp[-3].var_id).id, (yyvsp[-1].node));
    }
#line 2063 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 87: /* UnaryExp: T_ADD UnaryExp  */
#line 578 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_POSITIVE,(yyvsp[0].node),nullptr);
	}
#line 2071 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 88: /* UnaryExp: T_SUB UnaryExp  */
#line 582 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_NEGATIVE,(yyvsp[0].node),nullptr);
		
	}
#line 2080 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 89: /* UnaryExp: T_NOT UnaryExp  */
#line 587 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
        //$$ = new_ast_node(ast_operator_type::AST_OP_EXPR_SHOW, $1, nullptr);
		// 
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_NOT,(yyvsp[0].node),nullptr);
	}
#line 2090 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 90: /* PrimaryExp: '(' Expr ')'  */
#line 593 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                           {
        /* PrimaryExp = Expr */
        (yyval.node) = (yyvsp[-1].node);
    }
#line 2099 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 91: /* PrimaryExp: T_DIGIT  */
#line 597 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
              {
        // 无符号整数识别

        // 终结符作为抽象语法树的叶子节点进行创建
        (yyval.node) = new_ast_leaf_node(digit_int_attr{(yyvsp[0].integer_num).val, (yyvsp[0].integer_num).lineno});
    }
#line 2110 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 92: /* PrimaryExp: LVal  */
#line 603 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
            {
        // 左值
        (yyval.node) = (yyvsp[0].node);
    }
#line 2119 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 93: /* LVal: T_ID  */
#line 610 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
            {
        // 终结符作为抽象语法树的叶子节点进行创建
        (yyval.node) = new_ast_leaf_node(var_id_attr{(yyvsp[0].var_id).id, (yyvsp[0].var_id).lineno});

		// 对于字符型字面量的字符串空间需要释放，因词法用到了strdup进行了字符串复制
		free((yyvsp[0].var_id).id);
    }
#line 2131 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 94: /* LVal: T_ID LValueList  */
#line 618 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		ast_node *id_node = new_ast_leaf_node(var_id_attr{(yyvsp[-1].var_id).id, (yyvsp[-1].var_id).lineno});
        ast_node *return_node = create_contain_node(ast_operator_type::AST_OP_ARRAY_VISIT, id_node);
		(yyval.node) = insert_ast_node(return_node, (yyvsp[0].node));
	}
#line 2141 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 95: /* LValueList: '[' Expr ']'  */
#line 625 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		// ast_node *id_node = new_ast_leaf_node(var_id_attr{$2.id, $2.lineno});
		// ast_node * info_node = new_info_node(ast_operator_type::AST_OP_INFO_ARRAY_VISIT,$2.val);
		// ast_node * info_node = new_ast_node(ast_operator_type::AST_OP_INFO_ARRAY_VISIT,$2,nullptr);
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_INFO_ARRAY_VISIT, (yyvsp[-1].node));

	}
#line 2153 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 96: /* LValueList: LValueList '[' Expr ']'  */
#line 633 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
        {
		// ast_node * info_node = new_info_node(ast_operator_type::AST_OP_INFO_ARRAY_VISIT,$3.val);
		// ast_node * info_node = new_ast_node(ast_operator_type::AST_OP_INFO_ARRAY_VISIT,$3,nullptr);
		(yyval.node) = insert_ast_node((yyvsp[-3].node), (yyvsp[-1].node));
	}
#line 2163 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 97: /* RealParamList: Expr  */
#line 642 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                     {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_FUNC_REAL_PARAMS, (yyvsp[0].node));
    }
#line 2171 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;

  case 98: /* RealParamList: RealParamList ',' Expr  */
#line 645 "/home/zhao/calculator/frontend/flexbison/Calculator.y"
                             {
        (yyval.node) = insert_ast_node((yyvsp[-2].node), (yyvsp[0].node));
    }
#line 2179 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"
    break;


#line 2183 "/home/zhao/calculator/frontend/flexbison/autogenerated/CalculatorBison.cpp"

      default: break;
    }
  /* User semantic actions sometimes alter yychar, and that requires
     that yytoken be updated with the new translation.  We take the
     approach of translating immediately before every use of yytoken.
     One alternative is translating here after every semantic action,
     but that translation would be missed if the semantic action invokes
     YYABORT, YYACCEPT, or YYERROR immediately after altering yychar or
     if it invokes YYBACKUP.  In the case of YYABORT or YYACCEPT, an
     incorrect destructor might then be invoked immediately.  In the
     case of YYERROR or YYBACKUP, subsequent parser actions might lead
     to an incorrect destructor call or verbose syntax error message
     before the lookahead is translated.  */
  YY_SYMBOL_PRINT ("-> $$ =", YY_CAST (yysymbol_kind_t, yyr1[yyn]), &yyval, &yyloc);

  YYPOPSTACK (yylen);
  yylen = 0;

  *++yyvsp = yyval;

  /* Now 'shift' the result of the reduction.  Determine what state
     that goes to, based on the state we popped back to and the rule
     number reduced by.  */
  {
    const int yylhs = yyr1[yyn] - YYNTOKENS;
    const int yyi = yypgoto[yylhs] + *yyssp;
    yystate = (0 <= yyi && yyi <= YYLAST && yycheck[yyi] == *yyssp
               ? yytable[yyi]
               : yydefgoto[yylhs]);
  }

  goto yynewstate;


/*--------------------------------------.
| yyerrlab -- here on detecting error.  |
`--------------------------------------*/
yyerrlab:
  /* Make sure we have latest lookahead translation.  See comments at
     user semantic actions for why this is necessary.  */
  yytoken = yychar == YYEMPTY ? YYSYMBOL_YYEMPTY : YYTRANSLATE (yychar);
  /* If not already recovering from an error, report this error.  */
  if (!yyerrstatus)
    {
      ++yynerrs;
      yyerror (YY_("syntax error"));
    }

  if (yyerrstatus == 3)
    {
      /* If just tried and failed to reuse lookahead token after an
         error, discard it.  */

      if (yychar <= YYEOF)
        {
          /* Return failure if at end of input.  */
          if (yychar == YYEOF)
            YYABORT;
        }
      else
        {
          yydestruct ("Error: discarding",
                      yytoken, &yylval);
          yychar = YYEMPTY;
        }
    }

  /* Else will try to reuse lookahead token after shifting the error
     token.  */
  goto yyerrlab1;


/*---------------------------------------------------.
| yyerrorlab -- error raised explicitly by YYERROR.  |
`---------------------------------------------------*/
yyerrorlab:
  /* Pacify compilers when the user code never invokes YYERROR and the
     label yyerrorlab therefore never appears in user code.  */
  if (0)
    YYERROR;
  ++yynerrs;

  /* Do not reclaim the symbols of the rule whose action triggered
     this YYERROR.  */
  YYPOPSTACK (yylen);
  yylen = 0;
  YY_STACK_PRINT (yyss, yyssp);
  yystate = *yyssp;
  goto yyerrlab1;


/*-------------------------------------------------------------.
| yyerrlab1 -- common code for both syntax error and YYERROR.  |
`-------------------------------------------------------------*/
yyerrlab1:
  yyerrstatus = 3;      /* Each real token shifted decrements this.  */

  /* Pop stack until we find a state that shifts the error token.  */
  for (;;)
    {
      yyn = yypact[yystate];
      if (!yypact_value_is_default (yyn))
        {
          yyn += YYSYMBOL_YYerror;
          if (0 <= yyn && yyn <= YYLAST && yycheck[yyn] == YYSYMBOL_YYerror)
            {
              yyn = yytable[yyn];
              if (0 < yyn)
                break;
            }
        }

      /* Pop the current state because it cannot handle the error token.  */
      if (yyssp == yyss)
        YYABORT;


      yydestruct ("Error: popping",
                  YY_ACCESSING_SYMBOL (yystate), yyvsp);
      YYPOPSTACK (1);
      yystate = *yyssp;
      YY_STACK_PRINT (yyss, yyssp);
    }

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END


  /* Shift the error token.  */
  YY_SYMBOL_PRINT ("Shifting", YY_ACCESSING_SYMBOL (yyn), yyvsp, yylsp);

  yystate = yyn;
  goto yynewstate;


/*-------------------------------------.
| yyacceptlab -- YYACCEPT comes here.  |
`-------------------------------------*/
yyacceptlab:
  yyresult = 0;
  goto yyreturnlab;


/*-----------------------------------.
| yyabortlab -- YYABORT comes here.  |
`-----------------------------------*/
yyabortlab:
  yyresult = 1;
  goto yyreturnlab;


/*-----------------------------------------------------------.
| yyexhaustedlab -- YYNOMEM (memory exhaustion) comes here.  |
`-----------------------------------------------------------*/
yyexhaustedlab:
  yyerror (YY_("memory exhausted"));
  yyresult = 2;
  goto yyreturnlab;


/*----------------------------------------------------------.
| yyreturnlab -- parsing is finished, clean up and return.  |
`----------------------------------------------------------*/
yyreturnlab:
  if (yychar != YYEMPTY)
    {
      /* Make sure we have latest lookahead translation.  See comments at
         user semantic actions for why this is necessary.  */
      yytoken = YYTRANSLATE (yychar);
      yydestruct ("Cleanup: discarding lookahead",
                  yytoken, &yylval);
    }
  /* Do not reclaim the symbols of the rule whose action triggered
     this YYABORT or YYACCEPT.  */
  YYPOPSTACK (yylen);
  YY_STACK_PRINT (yyss, yyssp);
  while (yyssp != yyss)
    {
      yydestruct ("Cleanup: popping",
                  YY_ACCESSING_SYMBOL (+*yyssp), yyvsp);
      YYPOPSTACK (1);
    }
#ifndef yyoverflow
  if (yyss != yyssa)
    YYSTACK_FREE (yyss);
#endif

  return yyresult;
}

#line 649 "/home/zhao/calculator/frontend/flexbison/Calculator.y"


// 语法识别错误要调用函数的定义
void yyerror(char * msg)
{
    printf("Line %d: %s\n", yylineno, msg);
}
